const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const M=require('./manufacturing-list.js');

const recapText=['17.127\t3\tA-Rosas-Colores-50_3\t10\t4\t12\t-8\t1\t17127-3','17.127\t4\tA-Rosas-Colores-60_4\t3\t1\t1\t-3\t\t17127-4','50.971\t3\tC-BLEU-PARFUME-3\t4\t2\t3\t-1\t\t50971-3','18.397\t2\tS-Lilium-Rosa-2\t0\t0\t1\t-1\t\t18397-2','9.031\t1\tP-Bonsai\t2\t0\t0\t0\t\t9031-1'].join('\n');
const salesText=['Produits de production - Commandes par niveau de prix du 01082026 au 06082026','code\ttype\treference\tTotal\t001\t002\t003\t004','17127\tRose\tA-Rosas-Colores-30-40-50-60\t149\t14\t2\t115\t18','50971\tBouquet\tC-BLEU-PARFUME\t12\t1\t5\t6\t0','18397\tBouquet\tS-Lilium-Rosa\t7\t0\t7\t0\t0','9031\tPlante\tP-Bonsai\t2\t2\t0\t0\t0','TOTAL\t\t\t170'].join('\n');
const nomenclatures=[{productCode:'17127',category:'ROSAS',manufacturingRates:[14,12,10,10],sizes:['30 cm','40 cm','50 cm','60 cm']},{productCode:'50971',category:'COMPUESTOS',manufacturingRates:[10,9,8]},{productCode:'18397',category:'SIMPLES',manufacturingRates:[14,12]},{productCode:'9031',category:'PLANTAS',manufacturingRates:[5]},{productCode:'35641',category:'COMPUESTOS',manufacturingRates:[10,9,8]}];
const florists=[{id:'ana',name:'Ana',hours:3},{id:'marta',name:'Marta',hours:4},{id:'lucia',name:'Lucía',hours:2.5}];
const parsed=()=>({recap:M.parseManufacturingRecap(recapText),sales:M.parseSalesByPrice(salesText)});
const generated=()=>{const p=parsed();return M.generateManufacturingLists({recapRows:p.recap.rows,salesRows:p.sales.rows,salesPeriodDays:p.sales.period.days,florists,nomenclatures});};

test('01 códigos con puntos se normalizan',()=>assert.equal(M.parseManufacturingRecap('17.127\t3\tRamo\t10').rows[0].productCode,'17127'));
test('02 celdas vacías conservan las columnas del Recap',()=>{const row=M.parseManufacturingRecap('17.127\t1\tRamo\t3\t1\t1\t\t\t17127-1').rows[0];assert.equal(row.solde,0);assert.equal(row.productPriceId,'17127-1');});
test('03 solde negativo se conserva',()=>assert.equal(parsed().recap.rows[0].solde,-8));
test('04 Prepa cero se conserva como cero',()=>assert.equal(parsed().recap.rows.find(row=>row.key==='18397-2').prepa,0));
test('05 ventas P1 a P4 se leen por nivel',()=>assert.deepEqual(parsed().sales.rows[0].salesByPrice,{1:14,2:2,3:115,4:18}));
test('06 periodo de ventas se detecta inclusivo',()=>assert.deepEqual(parsed().sales.period,{start:'2026-08-01',end:'2026-08-06',days:6}));
test('07 el cruce usa código y nivel',()=>{const p=parsed(),n=M.normalizeManufacturingInputs({recapRows:p.recap.rows,salesRows:p.sales.rows,salesPeriodDays:6,nomenclatures});assert.equal(n.rows.find(row=>row.key==='17127-3').levelSales,115);});
test('08 guiones y guiones bajos no impiden el cruce',()=>{const r=M.parseManufacturingRecap('17.127\t3\tA_Rosas-Colores_3\t2\t0\t0\t-1').rows[0];assert.equal(r.key,'17127-3');});
test('09 TOTAL se ignora en ventas',()=>assert.equal(parsed().sales.rows.length,4));

const filterCase=(name,type,reference,category,included)=>test(name,()=>{const result=M.filterManufacturableProducts([{type,reference,category}]);assert.equal(result.included.length,included?1:0);});
filterCase('10 incluye Bouquet','Bouquet','C-Test','COMPUESTOS',true);
filterCase('11 incluye Rose','Rose','A-Test','ROSAS',true);
filterCase('12 incluye compuestos internos','','C-Test','COMPUESTOS',true);
filterCase('13 excluye Plante','Plante','P-Test','PLANTAS',false);
filterCase('14 excluye Service','Service','X','',false);
filterCase('15 excluye Cadeau','Cadeau','Regalo','',false);
filterCase('16 excluye Deuil','Deuil','Corona','',false);
filterCase('17 excluye TF-','Bouquet','TF-Rosa','COMPUESTOS',false);
filterCase('18 excluye X-Foto','Service','X-Foto','',false);

test('19 solde -8 tiene prioridad sobre solde -1',()=>{const a=M.calculateManufacturingPriority({solde:-8,dailySales:1,productCode:'2',priceLevel:1}),b=M.calculateManufacturingPriority({solde:-1,dailySales:100,productCode:'1',priceLevel:1});assert.ok(a.severity>b.severity);});
test('20 un solde negativo se asigna antes que prevención',()=>{const result=M.assignManufacturingBlocks([{key:'A-1',productCode:'A',priceLevel:1,reference:'A',type:'Rose',category:'ROSAS',prepa:1,solde:0,dailySales:100,theoreticalNeed:1,rate:1},{key:'B-1',productCode:'B',priceLevel:1,reference:'B',type:'Rose',category:'ROSAS',prepa:1,solde:-1,dailySales:1,theoreticalNeed:2,rate:1}],[{name:'Ana',hours:1}]);assert.equal(result.lists[0].lines[0].key,'B-1');});
test('21 mayor venta diaria gana con el mismo solde',()=>{const rows=[{key:'A-1',productCode:'A',priceLevel:1,reference:'A',type:'Rose',category:'ROSAS',prepa:1,solde:0,dailySales:1,theoreticalNeed:1,rate:1},{key:'B-1',productCode:'B',priceLevel:1,reference:'B',type:'Rose',category:'ROSAS',prepa:1,solde:0,dailySales:2,theoreticalNeed:1,rate:1}],result=M.assignManufacturingBlocks(rows,[{name:'Ana',hours:1}]);assert.equal(result.lists[0].lines[0].key,'B-1');});
test('22 sin ventas y sin solde negativo no entra',()=>{const result=M.assignManufacturingBlocks([{key:'A-1',productCode:'A',reference:'A',type:'Rose',category:'ROSAS',prepa:2,solde:0,dailySales:0,theoreticalNeed:0,rate:1}],[{hours:3}]);assert.equal(result.lists[0].lines.length,0);});

test('23 nunca supera Prepa',()=>{const line=generated().lists.flatMap(list=>list.lines).find(row=>row.key==='17127-3');assert.ok(line.assignedQuantity<=10);});
test('24 Prepa cero no se asigna',()=>assert.ok(!generated().lists.flatMap(list=>list.lines).some(row=>row.key==='18397-2')));
test('25 varias floristas comparten un único saldo Prepa',()=>{const result=generated(),sum=result.lists.flatMap(list=>list.lines).filter(row=>row.key==='17127-3').reduce((a,b)=>a+b.assignedQuantity,0);assert.ok(sum<=10);});
test('26 una referencia no reutiliza Prepa',()=>{const keys=generated().lists.flatMap(list=>list.lines).map(row=>row.key);assert.equal(keys.length,new Set(keys).size);});
test('27 falta de Prepa genera aviso',()=>assert.equal(generated().unassigned.find(row=>row.key==='18397-2').reasonCode,'NO_PREPA'));
test('28 separa necesidad, asignado y pendiente',()=>{const line=generated().lists.flatMap(list=>list.lines).find(row=>row.key==='17127-3');assert.ok(line.theoreticalNeed>=line.assignedQuantity);assert.equal(line.pendingQuantity,line.theoreticalNeed-line.assignedQuantity);});

test('29 nunca supera horas disponibles',()=>generated().lists.forEach(list=>assert.ok(list.assignedHours<=list.availableHours+1e-9)));
test('30 unidades por tiempo usan floor',()=>assert.equal(M.calculateAssignableQuantity({theoreticalPending:10,prepaAvailable:10,hoursRemaining:.99,rate:3}),2));
test('31 no añade una unidad que excede las horas',()=>assert.equal(M.calculateAssignableQuantity({theoreticalPending:10,prepaAvailable:10,hoursRemaining:.333,rate:3}),0));
test('32 aplica rendimiento exacto',()=>{const p=parsed(),n=M.normalizeManufacturingInputs({recapRows:p.recap.rows,salesRows:p.sales.rows,salesPeriodDays:6,nomenclatures});assert.equal(n.rows.find(row=>row.key==='17127-3').rate,10);assert.equal(n.rows.find(row=>row.key==='17127-3').source,'exact');});
test('33 usa media de producto',()=>{const n=M.normalizeManufacturingInputs({recapRows:[{productCode:'17127',priceLevel:5,reference:'Rose',type:'Rose',category:'ROSAS',prepa:1,solde:-1}],salesRows:[],nomenclatures});assert.equal(n.rows[0].source,'product-average');assert.equal(n.rows[0].rate,11.5);});
test('33b pondera la media del producto con las ventas por nivel disponibles',()=>{const n=M.normalizeManufacturingInputs({recapRows:[{productCode:'17127',priceLevel:5,reference:'Rose',type:'Rose',category:'ROSAS',prepa:1,solde:-1}],salesRows:[{productCode:'17127',salesByPrice:{1:1,2:1,3:8,4:0}}],nomenclatures});assert.equal(n.rows[0].source,'product-average');assert.equal(n.rows[0].rate,10.6);});
test('34 usa media de categoría',()=>{const n=M.normalizeManufacturingInputs({recapRows:[{productCode:'999',priceLevel:1,reference:'Compuesto',type:'Bouquet',category:'COMPUESTOS',prepa:1,solde:-1}],salesRows:[],nomenclatures});assert.equal(n.rows[0].source,'category-average');assert.ok(n.rows[0].rate>0);});
test('35 sin rendimiento no asigna',()=>{const result=M.generateManufacturingLists({recapRows:[{productCode:'999',priceLevel:1,reference:'Rose',type:'Rose',category:'ROSAS',prepa:2,solde:-1}],florists:[{hours:2}],nomenclatures:[]});assert.equal(result.lists[0].lines.length,0);assert.equal(result.unassigned[0].reasonCode,'NO_RATE');});

test('36 una referencia aparece en una sola florista',()=>{const matches=generated().lists.filter(list=>list.lines.some(row=>row.key==='17127-3'));assert.equal(matches.length,1);});
test('37 una referencia grande se reduce pero no se divide',()=>{const result=M.assignManufacturingBlocks([{key:'A-1',productCode:'A',reference:'A',type:'Rose',category:'ROSAS',prepa:10,solde:-10,dailySales:1,theoreticalNeed:20,rate:2}],[{name:'A',hours:2},{name:'B',hours:2}]);assert.equal(result.lists.flatMap(list=>list.lines).length,1);assert.equal(result.lists.flatMap(list=>list.lines)[0].assignedQuantity,4);});
test('38 agrupa niveles del mismo código cuando caben',()=>{const rows=[1,2].map(level=>({key:`A-${level}`,productCode:'A',priceLevel:level,reference:'A',type:'Rose',category:'ROSAS',prepa:1,solde:-1,dailySales:1,theoreticalNeed:2,rate:1})),result=M.assignManufacturingBlocks(rows,[{name:'A',hours:2},{name:'B',hours:2}]);assert.equal(result.lists.find(list=>list.lines.some(row=>row.key==='A-1')).id,result.lists.find(list=>list.lines.some(row=>row.key==='A-2')).id);});
test('39 prioridad urgente prevalece sobre agrupación',()=>{const result=M.assignManufacturingBlocks([{key:'A-1',productCode:'A',priceLevel:1,reference:'A',type:'Rose',category:'ROSAS',prepa:1,solde:0,dailySales:10,theoreticalNeed:1,rate:1},{key:'B-1',productCode:'B',priceLevel:1,reference:'B',type:'Rose',category:'ROSAS',prepa:1,solde:-1,dailySales:1,theoreticalNeed:2,rate:1}],[{hours:1}]);assert.equal(result.lists[0].lines[0].key,'B-1');});
test('40 el resultado es determinista',()=>assert.deepEqual(generated(),generated()));
test('41 respeta horas por florista',()=>generated().lists.forEach(list=>assert.ok(list.remainingHours>=0)));
test('42 nombres y horas son independientes',()=>assert.deepEqual(generated().lists.map(list=>[list.name,list.availableHours]),[['Ana',3],['Marta',4],['Lucía',2.5]]));
test('42b equilibra la ocupación cuando no existe afinidad de familia o categoría',()=>{const result=generated(),rose=result.lists.find(list=>list.lines.some(row=>row.key==='17127-3')),compound=result.lists.find(list=>list.lines.some(row=>row.key==='50971-3'));assert.notEqual(rose.id,compound.id);});

test('43 mover referencia cambia la florista completa',()=>{const result=generated(),line=result.lists.flatMap(list=>list.lines)[0],target=result.lists.find(list=>list.id!==line.floristId),edited=M.editManufacturingLists(result,{type:'move',key:line.key,floristId:target.id});assert.equal(edited.lists.find(list=>list.id===target.id).lines.filter(row=>row.key===line.key).length,1);});
test('44 añadir una referencia duplicada se rechaza',()=>{const result=generated(),line=result.lists.flatMap(list=>list.lines)[0];assert.throws(()=>M.editManufacturingLists(result,{type:'add',key:line.key,floristId:result.lists[0].id,quantity:1}),/ya está asignada/);});
test('45 exceso de Prepa se rechaza en validación',()=>{const result=generated(),line=result.lists.flatMap(list=>list.lines)[0];line.assignedQuantity=line.prepa+1;assert.equal(M.validateManufacturingLists(result).ok,false);});
test('46 exceso de horas se rechaza en validación',()=>{const result=generated(),line=result.lists.flatMap(list=>list.lines)[0],list=result.lists.find(item=>item.id===line.floristId);line.assignedQuantity=Math.ceil(list.availableHours*line.rate)+1;assert.ok(M.validateManufacturingLists(result).errors.some(error=>error.includes('horas')));});
test('47 eliminar devuelve Prepa al saldo disponible',()=>{const result=generated(),line=result.lists.flatMap(list=>list.lines)[0],before=result.availablePrepa[line.key],edited=M.editManufacturingLists(result,{type:'remove',key:line.key});assert.equal(edited.availablePrepa[line.key],before+line.assignedQuantity);});

test('48 modelo de impresión individual contiene una lista',()=>{const result=generated(),model=M.buildManufacturingPrintModel(result,{floristId:result.lists[0].id});assert.equal(model.pages.length,1);});
test('49 modelo conjunto omite listas vacías',()=>assert.equal(M.buildManufacturingPrintModel(generated()).pages.length,2));
test('50 modelo conjunto crea una página por florista con trabajo',()=>assert.deepEqual(M.buildManufacturingPrintModel(generated()).pages.map(page=>page.name),['Ana','Lucía']));
test('51 impresión no repite pendientes en cada página',()=>assert.ok(M.buildManufacturingPrintModel(generated()).pages.every(page=>!Object.hasOwn(page,'unassigned'))));
test('52 modelo de impresión no contiene controles',()=>assert.equal(M.buildManufacturingPrintModel(generated()).containsControls,false));

test('53 guardar borrador conserva propuesta',()=>{const proposal=generated(),draft=M.createManufacturingDraft({proposal});assert.equal(draft.status,'draft');assert.deepEqual(draft.proposal,proposal);});
test('54 recargar borrador conserva modificaciones',()=>{const draft=M.createManufacturingDraft({modifications:[{type:'move',key:'17127-3'}]}),reload=JSON.parse(JSON.stringify(draft));assert.deepEqual(reload.modifications,draft.modifications);});
test('55 generar no altera el stock de entrada',()=>{const p=parsed(),before=JSON.stringify(p.recap.rows);M.generateManufacturingLists({recapRows:p.recap.rows,salesRows:p.sales.rows,salesPeriodDays:6,florists,nomenclatures});assert.equal(JSON.stringify(p.recap.rows),before);});
test('56 el módulo puro no escribe automáticamente en Supabase',()=>{const source=fs.readFileSync(path.join(__dirname,'manufacturing-list.js'),'utf8');assert.doesNotMatch(source,/supabaseClient|\.from\('app_states'\)|saveState\(/);});

test('datos reales solicitados respetan máximos y exclusiones',()=>{const result=generated(),lines=result.lists.flatMap(list=>list.lines),byKey=new Map(lines.map(line=>[line.key,line]));assert.ok(byKey.get('17127-3').assignedQuantity<=10);assert.ok(byKey.get('17127-4').assignedQuantity<=3);assert.ok(byKey.get('50971-3').assignedQuantity<=4);assert.ok(!byKey.has('18397-2'));assert.ok(result.unassigned.some(row=>row.key==='9031-1'&&row.reasonCode==='EXCLUDED'));});
test('el resultado resume las exclusiones por motivo',()=>assert.equal(generated().exclusionSummary.Planta,1));
test('los fixtures Bonsái, Orquídeas, Anthurium, X-Foto y TF quedan excluidos',()=>{const rows=[['P-Bonsai','Plante'],['P-Orqui-BLANCA','Plante'],['P-Orqui-ROSA','Plante'],['P-Anthurium','Plante'],['X-Foto','Service'],['TF-Rosa-AQ004','Bouquet']].map(([reference,type],index)=>({productCode:String(index+1),priceLevel:1,reference,type,category:type==='Plante'?'PLANTAS':'',prepa:1,rate:1})),filtered=M.filterManufacturableProducts(rows);assert.equal(filtered.included.length,0);assert.equal(filtered.excluded.length,6);assert.ok(filtered.excluded.every(row=>row.reason));});

test('la edición recalcula resumen y saldo Prepa',()=>{const result=generated(),line=result.lists.flatMap(list=>list.lines)[0],edited=M.editManufacturingLists(result,{type:'quantity',key:line.key,quantity:1});assert.equal(edited.availablePrepa[line.key],line.prepa-1);assert.equal(edited.summary.assignedUnits,edited.lists.reduce((sum,list)=>sum+list.units,0));});
test('la edición manual no permite añadir un producto excluido',()=>{const result=generated(),target=result.lists[0];assert.throws(()=>M.editManufacturingLists(result,{type:'add',key:'9031-1',floristId:target.id,quantity:1}),/excluido/);});
test('la interfaz solo persiste la propuesta al pulsar Guardar borrador',()=>{const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8'),generate=html.match(/function generateManufacturingListProposal\(\)\{[^\n]+/)?.[0]||'',save=html.match(/btnSaveManufacturingDraft'\)\.addEventListener\('click',[^\n]+/)?.[0]||'';assert.doesNotMatch(generate,/saveState\(/);assert.match(save,/saveState\(\)/);});

const htmlSource=()=>fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const productionSideMenu=()=>htmlSource().match(/<div class="side-nav-actions" data-actions-for="production">([\s\S]*?)<\/div>/)?.[1]||'';
const urgentCase=({solde=-3,prepa=10,rate=1,hours=1,category='ROSAS',type='Rose'}={})=>M.generateManufacturingLists({recapRows:[{key:'900-1',productCode:'900',priceLevel:1,reference:'A-Rosas-Urgente',prepa,solde,type,category}],salesRows:[],salesPeriodDays:1,florists:[{id:'ana',name:'Ana',hours}],nomenclatures:rate?[{productCode:'900',category,manufacturingRates:[rate]}]:[]});

test('ajuste 01 Lista de fabricación aparece en el menú lateral',()=>assert.match(productionSideMenu(),/data-production-nav="manufacturing-list">Lista de fabricación/));
test('ajuste 02 está debajo de Planificación semanal',()=>{const menu=productionSideMenu();assert.ok(menu.indexOf('data-production-nav="weekly"')<menu.indexOf('data-production-nav="manufacturing-list"'));});
test('ajuste 03 el acceso lateral abre la pestaña correcta',()=>assert.match(htmlSource(),/setProductionTab\(button\.dataset\.productionNav\)/));
test('ajuste 04 el acceso lateral se marca activo',()=>assert.match(htmlSource(),/data-production-nav[^\n]+classList\.toggle\('active'/));

test('ajuste 05 no hay controles de archivo en Lista de fabricación',()=>{const panel=htmlSource().match(/data-production-panel="manufacturing-list"([\s\S]*?)data-production-panel="times"/)?.[1]||'';assert.doesNotMatch(panel,/type="file"|Cargar archivo|seleccionar archivo|importar fichero/i);});
test('ajuste 06 Recap de hoy se valida desde textarea',()=>{const html=htmlSource();assert.match(html,/id="manufacturingTodayRecapInput"/);assert.match(html,/id="btnValidateManufacturingTodayRecap"/);});
test('ajuste 07 ventas se validan desde textarea',()=>{const html=htmlSource();assert.match(html,/id="manufacturingSalesInput"/);assert.match(html,/id="btnValidateManufacturingSales"/);});
test('ajuste 08 editar recap de hoy invalida su validación',()=>assert.match(htmlSource(),/manufacturingTodayRecapInput'\)\.addEventListener\('input'[^\n]+invalidateManufacturingInput\('todayRecap'\)/));
test('ajuste 09 solo recap de hoy bloquea la generación',()=>{const source=htmlSource().match(/function generateManufacturingListProposal\(\)\{[^\n]+/)?.[0]||'';assert.match(source,/validation\.todayRecap!=='validated'/);assert.doesNotMatch(source,/validation\.sales!=='validated'\)\{/);});

test('ajuste 10 solde negativo sin Prepa aparece',()=>{const urgency=M.manufacturingUrgencies(urgentCase({prepa:0,hours:2}))[0];assert.equal(urgency.reasonCode,'NO_PREPA');assert.equal(urgency.pendingQuantity,3);});
test('ajuste 11 solde negativo sin tiempo aparece',()=>{const urgency=M.manufacturingUrgencies(urgentCase())[0];assert.equal(urgency.reasonCode,'NO_TIME');assert.equal(urgency.pendingQuantity,2);});
test('ajuste 12 solde negativo sin rendimiento aparece',()=>{const urgency=M.manufacturingUrgencies(urgentCase({rate:0,hours:3}))[0];assert.equal(urgency.reasonCode,'NO_RATE');});
test('ajuste 13 reposición preventiva no asignada no aparece',()=>assert.deepEqual(M.manufacturingUrgencies(urgentCase({solde:0,prepa:5,hours:0})),[]));
test('ajuste 14 producto con solde positivo no aparece',()=>assert.deepEqual(M.manufacturingUrgencies(urgentCase({solde:2,prepa:5,hours:0})),[]));
test('ajuste 15 exclusión sin solde negativo no aparece',()=>assert.deepEqual(M.manufacturingUrgencies(urgentCase({solde:0,category:'PLANTAS',type:'Plante'})),[]));

test('ajuste 16 total general de ramos se expone siempre en el resultado',()=>assert.match(htmlSource(),/id="manufacturingGrandTotals"[\s\S]*?Total a fabricar/));
test('ajuste 17 total por florista es correcto',()=>{const result=generated(),totals=M.summarizeManufacturingLists(result);totals.lists.forEach(total=>assert.equal(total.units,result.lists.find(list=>list.id===total.id).lines.reduce((sum,line)=>sum+line.assignedQuantity,0)));});
test('ajuste 18 cambiar cantidad actualiza total',()=>{const result=generated(),line=result.lists.flatMap(list=>list.lines)[0],edited=M.editManufacturingLists(result,{type:'quantity',key:line.key,quantity:1});assert.equal(M.summarizeManufacturingLists(edited).units,M.summarizeManufacturingLists(result).units-line.assignedQuantity+1);});
test('ajuste 19 eliminar línea actualiza total',()=>{const result=generated(),line=result.lists.flatMap(list=>list.lines)[0],edited=M.editManufacturingLists(result,{type:'remove',key:line.key});assert.equal(M.summarizeManufacturingLists(edited).units,M.summarizeManufacturingLists(result).units-line.assignedQuantity);});
test('ajuste 20 mover referencia actualiza ambos subtotales',()=>{const result=generated(),line=result.lists.flatMap(list=>list.lines)[0],origin=line.floristId,target=result.lists.find(list=>list.id!==origin).id,edited=M.editManufacturingLists(result,{type:'move',key:line.key,floristId:target}),totals=M.summarizeManufacturingLists(edited);assert.equal(totals.lists.find(list=>list.id===origin).units,0);assert.ok(totals.lists.find(list=>list.id===target).units>=line.assignedQuantity);});
test('ajuste 21 total del PDF coincide con la tabla',()=>{const result=generated(),model=M.buildManufacturingPrintModel(result);assert.equal(model.totalUnits,M.summarizeManufacturingLists(result).units);});

test('ajuste 22 PDF no incluye Prepa',()=>assert.ok(M.buildManufacturingPrintModel(generated()).pages.every(page=>!JSON.stringify(page).includes('prepa'))));
test('ajuste 23 PDF no incluye solde',()=>assert.ok(M.buildManufacturingPrintModel(generated()).pages.every(page=>!JSON.stringify(page).includes('solde'))));
test('ajuste 24 PDF no incluye ventas',()=>assert.ok(M.buildManufacturingPrintModel(generated()).pages.every(page=>!JSON.stringify(page).includes('levelSales'))));
test('ajuste 25 PDF no incluye rendimiento',()=>assert.ok(M.buildManufacturingPrintModel(generated()).pages.every(page=>!JSON.stringify(page).includes('rate'))));
test('ajuste 26 PDF no incluye tiempo por línea',()=>assert.ok(M.buildManufacturingPrintModel(generated()).pages.every(page=>!JSON.stringify(page).includes('hours'))));
test('ajuste 27 PDF contiene orden, ramo, nivel, cantidad, prioridad y hecho',()=>{const line=M.buildManufacturingPrintModel(generated()).pages[0].groups[0].lines[0];assert.deepEqual(Object.keys(line),['order','reference','level','quantity','priorityToday','done','group','isUrgent']);});
test('ajuste 28 PDF agrupa Rosas',()=>assert.equal(M.classifyManufacturingPrintGroup({category:'ROSAS',type:'Rose',reference:'A-Rosas'}),'roses'));
test('ajuste 29 PDF agrupa Compuestos',()=>assert.equal(M.classifyManufacturingPrintGroup({category:'COMPUESTOS',type:'Bouquet',reference:'C-Toscana'}),'composed'));
test('ajuste 30 PDF agrupa Ramos',()=>assert.equal(M.classifyManufacturingPrintGroup({category:'SIMPLES',type:'Bouquet',reference:'S-Lilium'}),'bouquets'));
test('ajuste 31 urgentes aparecen primero',()=>{const result=generated(),model=M.buildManufacturingPrintModel(result);model.pages.forEach(page=>{const lines=page.groups.flatMap(group=>group.lines),firstRegular=lines.findIndex(line=>!line.isUrgent);if(firstRegular>=0)assert.ok(lines.slice(firstRegular).every(line=>!line.isUrgent));assert.deepEqual(lines.map(line=>line.order),Array.from({length:lines.length},(_,index)=>index+1));});});
test('ajuste 32 hay una página por florista con trabajo',()=>{const result=generated(),model=M.buildManufacturingPrintModel(result);assert.equal(model.pages.length,result.lists.filter(list=>list.lines.length).length);});
test('ajuste 33 cada página muestra total de ramos',()=>M.buildManufacturingPrintModel(generated()).pages.forEach(page=>assert.ok(Number.isFinite(page.totalUnits))));
test('ajuste 34 total final coincide con suma de líneas',()=>M.buildManufacturingPrintModel(generated()).pages.forEach(page=>assert.equal(page.totalUnits,page.groups.flatMap(group=>group.lines).reduce((sum,line)=>sum+line.quantity,0))));
test('ajuste 35 no aparecen controles en impresión',()=>assert.equal(M.buildManufacturingPrintModel(generated()).containsControls,false));

const makeRow=({productCode='700',priceLevel=1,reference='Producto',prepa=100,solde=0,category='COMPUESTOS'}={})=>({key:`${productCode}-${priceLevel}`,productCode,priceLevel,reference,prepa,solde,category,type:category==='ROSAS'?'Rose':'Bouquet'});
const normalizeCase=({today, multi=[], sales=[], category=today.category||'COMPUESTOS'}={})=>M.normalizeManufacturingInputs({todayRecapRows:[today],multiDayRecapRows:multi,salesRows:sales,salesPeriodDays:2,nomenclatures:[{productCode:today.productCode,category,manufacturingRates:[10,10,10,10]}]}).rows[0];

test('evolución 01 recap hoy -8 conserva prioridad hoy 8',()=>{const row=normalizeCase({today:makeRow({solde:-8})});assert.equal(row.priorityToday,8);});
test('evolución 02 varios días incluye hoy sin duplicar',()=>{const today=makeRow({solde:-3}),future=makeRow({solde:-8}),row=normalizeCase({today,multi:[future]});assert.equal(row.multiDayAdditionalNeed,5);assert.equal(row.proposedQuantity,8);});
test('evolución 03 hoy sin déficit y varios días -4 da adicional 4',()=>{const today=makeRow(),future=makeRow({solde:-4}),row=normalizeCase({today,multi:[future]});assert.equal(row.priorityToday,0);assert.equal(row.multiDayAdditionalNeed,4);});
test('evolución 04 recap varios días no modifica el Prepa de hoy',()=>{const today=makeRow({prepa:12}),future=makeRow({prepa:999,solde:-4}),row=normalizeCase({today,multi:[future]});assert.equal(row.prepa,12);});
test('evolución 05 compuesto puede consumir todo el Prepa',()=>{const today=makeRow({prepa:10}),future=makeRow({prepa:500,solde:-20}),row=normalizeCase({today,multi:[future]});assert.equal(row.proposedQuantity,10);assert.equal(row.remainingPrepa,0);});
test('evolución 06 rosa reserva aproximadamente 20 por ciento',()=>{const q=M.calculateProposedQuantity({prepa:100,priorityToday:30,additionalRecommended:60,policy:'roses'});assert.deepEqual([q.reserveTarget,q.proposedQuantity,q.remainingPrepa],[20,80,20]);});
test('evolución 07 urgencia de rosa prevalece sobre reserva',()=>{const q=M.calculateProposedQuantity({prepa:100,priorityToday:90,additionalRecommended:30,policy:'roses'});assert.equal(q.proposedQuantity,90);assert.equal(q.effectiveReserve,10);});
test('evolución 08 rosa prepa 30 prioridad 8 adicional 12 fabrica 20',()=>assert.equal(M.calculateProposedQuantity({prepa:30,priorityToday:8,additionalRecommended:12,policy:'roses'}).proposedQuantity,20));
test('evolución 09 simple solo fabrica urgencia aunque haya futuro',()=>{const today=makeRow({productCode:'800',prepa:20,solde:-3,category:'SIMPLES'}),future=makeRow({productCode:'800',prepa:999,solde:-15,category:'SIMPLES'}),row=normalizeCase({today,multi:[future],category:'SIMPLES'});assert.equal(row.additionalRecommended,0);assert.equal(row.proposedQuantity,3);});
test('evolución 10 ventas altas no anticipan un simple',()=>{const today=makeRow({productCode:'801',prepa:20,category:'SIMPLES'}),row=normalizeCase({today,sales:[{productCode:'801',salesByPrice:{1:100}}],category:'SIMPLES'});assert.equal(row.levelSales,100);assert.equal(row.proposedQuantity,0);});
test('evolución 11 código 32486 usa política de rosas por código',()=>{const today=makeRow({productCode:'32.486',prepa:100,solde:-30,category:'SIMPLES'}),future=makeRow({productCode:'32486',prepa:1,solde:-90,category:'SIMPLES'}),row=normalizeCase({today,multi:[future],category:'SIMPLES'});assert.equal(row.policy,'roses');assert.equal(row.proposedQuantity,80);});
test('evolución 12 nombre premium con otro código sigue siendo simple',()=>{const today=makeRow({productCode:'32485',reference:'S-Premium-12-18-24-30-roja',prepa:100,solde:-30,category:'SIMPLES'}),future=makeRow({productCode:'32485',prepa:1,solde:-90,category:'SIMPLES'}),row=normalizeCase({today,multi:[future],category:'SIMPLES'});assert.equal(row.policy,'simple');assert.equal(row.proposedQuantity,30);});
test('evolución 13 prepa menor que urgencia conserva necesidad y descubierto',()=>{const row=normalizeCase({today:makeRow({prepa:6,solde:-10})});assert.equal(row.priorityToday,10);assert.equal(row.proposedQuantity,6);assert.equal(row.urgencyUncovered,4);});
test('evolución 14 prepa cero no produce NaN ni negativos',()=>{const row=normalizeCase({today:makeRow({prepa:0,solde:-4})});assert.equal(row.proposedQuantity,0);assert.equal(row.remainingPrepa,0);assert.ok(Number.isFinite(row.proposedQuantity));});
test('evolución 15 reserva redondea cantidades pequeñas',()=>assert.deepEqual([1,2,3,4,5].map(prepa=>M.calculateProposedQuantity({prepa,priorityToday:0,additionalRecommended:99,policy:'roses'}).reserveTarget),[0,0,1,1,1]));
test('evolución 16 ventas no se suman a la necesidad futura',()=>{const today=makeRow({prepa:100}),future=makeRow({solde:-5}),row=M.normalizeManufacturingInputs({todayRecapRows:[today],multiDayRecapRows:[future],salesRows:[{productCode:'700',salesByPrice:{1:6}}],salesPeriodDays:2,nomenclatures:[{productCode:'700',category:'COMPUESTOS',manufacturingRates:[10]}]}).rows[0];assert.equal(row.multiDayAdditionalNeed,5);assert.equal(row.salesSuggestedQuantity,3);assert.equal(row.additionalRecommended,5);});
test('evolución 17 ventas favorecen el nivel con mayor tendencia si falta tiempo',()=>{const rows=[makeRow({productCode:'710',priceLevel:1,reference:'Familia P1',prepa:5}),makeRow({productCode:'710',priceLevel:2,reference:'Familia P2',prepa:5})],future=rows.map(row=>({...row,solde:-2})),normalized=M.normalizeManufacturingInputs({todayRecapRows:rows,multiDayRecapRows:future,salesRows:[{productCode:'710',salesByPrice:{1:1,2:20}}],salesPeriodDays:2,nomenclatures:[{productCode:'710',category:'COMPUESTOS',manufacturingRates:[1,1]}]}),assigned=M.assignManufacturingBlocks(normalized.rows,[{hours:2}]);assert.equal(assigned.lists[0].lines[0].priceLevel,2);});
test('evolución 18 referencia futura sin hoy genera aviso y no inventa fila',()=>{const normalized=M.normalizeManufacturingInputs({todayRecapRows:[],multiDayRecapRows:[makeRow({solde:-4})]});assert.equal(normalized.rows.length,0);assert.equal(normalized.futureWithoutToday.length,1);});
test('evolución 19 edición manual conserva prioridad y limita al Prepa',()=>{const result=urgentCase({solde:-3,prepa:10,rate:2,hours:10}),line=result.lists[0].lines[0],edited=M.editManufacturingLists(result,{type:'quantity',key:line.key,quantity:99}).lists[0].lines[0];assert.equal(edited.assignedQuantity,10);assert.equal(edited.priorityToday,3);assert.equal(edited.remainingPrepa,0);});
test('evolución 20 orden visual categoría referencia y nivel',()=>{const rows=[makeRow({productCode:'3',category:'SIMPLES',reference:'A',priceLevel:1}),makeRow({productCode:'2',category:'ROSAS',reference:'B',priceLevel:1}),makeRow({productCode:'1',category:'ROSAS',reference:'A',priceLevel:2}),makeRow({productCode:'1',category:'ROSAS',reference:'A',priceLevel:1})].sort(M.compareManufacturingPresentation);assert.deepEqual(rows.map(row=>row.key),['1-1','1-2','2-1','3-1']);});
test('evolución 21 PDF conserva prioridad, hecho vacío y cantidad editada',()=>{const result=urgentCase({solde:-3,prepa:10,rate:2,hours:10}),key=result.lists[0].lines[0].key,edited=M.editManufacturingLists(result,{type:'quantity',key,quantity:7}),line=M.buildManufacturingPrintModel(edited).pages[0].groups[0].lines[0];assert.equal(line.quantity,7);assert.equal(line.priorityToday,3);assert.equal(line.done,'');assert.ok(!Object.hasOwn(line,'prepa'));});
test('evolución 22 tres acordeones existen y empiezan cerrados',()=>{const panel=htmlSource().match(/<div class="manufacturing-input-accordions">([\s\S]*?)<\/div>\s*<\/section>/)?.[1]||'';assert.equal((panel.match(/<details /g)||[]).length,3);assert.doesNotMatch(panel,/<details[^>]+\sopen(?:\s|>)/);});
test('evolución 23 estado migra recapText y conserva tres validaciones',()=>{const source=htmlSource().match(/function normalizeManufacturingListState\(value\)\{[^\n]+/)?.[0]||'';assert.match(source,/value\.todayRecapText\?\?value\.recapText\?\?''/);assert.match(source,/multiDayRecap/);});
test('evolución 24 tabla muestra prioridad, fabricar y stock Prepa',()=>{const source=htmlSource().match(/function renderManufacturingListsV3\(\)\{[^\n]+/)?.[0]||'';assert.match(source,/Prioridad hoy/);assert.match(source,/Stock Prepa disponible/);assert.match(source,/data-manufacturing-quantity/);});
test('evolución 25 impresión HTML incluye Hecho y no incluye stock Prepa',()=>{const source=htmlSource().match(/function printManufacturingLists\(floristId=null\)\{[\s\S]*?function productionDayOptions/)?.[0]||'';assert.match(source,/<th>Hecho<\/th>/);assert.doesNotMatch(source,/Stock Prepa/);});
test('evolución 26 sin datos secundarios se generan urgencias con avisos',()=>{const result=M.generateManufacturingLists({todayRecapRows:[makeRow({solde:-2,prepa:5})],multiDayValidated:false,salesValidated:false,florists:[{hours:2}],nomenclatures:[{productCode:'700',category:'COMPUESTOS',manufacturingRates:[2]}]});assert.equal(result.lists[0].lines[0].assignedQuantity,2);assert.equal(result.warnings.length,2);});
test('evolución 27 la interfaz muestra limitaciones de rendimiento y horas como avisos',()=>{const source=htmlSource().match(/function renderManufacturingLists\(\)\{[^\n]+/)?.[0]||'';assert.match(source,/NO_RATE/);assert.match(source,/NO_TIME/);assert.match(source,/Avisos/);});

const demandResult=({today,multi=[],sales=[],hours=20,nomenclatures:customNomenclatures}={})=>M.generateManufacturingLists({todayRecapRows:today,multiDayRecapRows:multi,salesRows:sales,salesPeriodDays:1,florists:[{id:'ana',name:'Ana',hours}],nomenclatures:customNomenclatures||[...new Map(today.map(row=>[row.productCode,{productCode:row.productCode,category:row.category,manufacturingRates:[10,10,10,10]}])).values()]});
const compoundFamily=()=>[makeRow({productCode:'9000',priceLevel:1,reference:'C-ASTRO-LEO_1',prepa:4,category:'COMPUESTOS'}),makeRow({productCode:'9000',priceLevel:2,reference:'C-ASTRO-LEO_2',prepa:0,solde:-2,category:'COMPUESTOS'}),makeRow({productCode:'9000',priceLevel:3,reference:'C-ASTRO-LEO_3',prepa:5,category:'COMPUESTOS'})];

test('dos fases 01 ventas con Prepa y horas generan anticipación sin urgencia',()=>{const today=[makeRow({prepa:10})],result=demandResult({today,sales:[{productCode:'700',salesByPrice:{1:3}}]});assert.equal(result.lists[0].lines[0].assignedQuantity,10);assert.ok(result.lists[0].lines[0].assignedQuantity>Math.ceil(result.lists[0].lines[0].dailySales));assert.equal(result.lists[0].lines[0].priorityToday,0);});
test('dos fases 02 dailySales 3 sugiere aproximadamente 3',()=>{const row=normalizeCase({today:makeRow({prepa:10}),sales:[{productCode:'700',salesByPrice:{1:6}}]});assert.equal(row.dailySales,3);assert.equal(row.salesSuggestedQuantity,3);assert.equal(row.additionalRecommended,3);});
test('dos fases 03 necesidad futura 5 y dailySales 3 elige 5, no 8',()=>{const row=M.normalizeManufacturingInputs({todayRecapRows:[makeRow({prepa:20})],multiDayRecapRows:[makeRow({solde:-5})],salesRows:[{productCode:'700',salesByPrice:{1:6}}],salesPeriodDays:2,nomenclatures:[{productCode:'700',category:'COMPUESTOS',manufacturingRates:[10]}]}).rows[0];assert.equal(row.additionalRecommended,5);});
test('dos fases 04 necesidad futura 2 y dailySales 5 elige 5',()=>{const row=normalizeCase({today:makeRow({prepa:20}),multi:[makeRow({solde:-2})],sales:[{productCode:'700',salesByPrice:{1:10}}]});assert.equal(row.dailySales,5);assert.equal(row.additionalRecommended,5);});
test('dos fases 05 las horas posteriores a urgencias se usan con candidatos razonables',()=>{const today=[makeRow({productCode:'701',prepa:4,solde:-2}),makeRow({productCode:'702',prepa:5})],result=demandResult({today,sales:[{productCode:'702',salesByPrice:{1:5}}],hours:.5});assert.equal(result.lists[0].lines.find(row=>row.productCode==='701').assignedQuantity,2);assert.equal(result.lists[0].lines.find(row=>row.productCode==='702').assignedQuantity,3);assert.equal(result.lists[0].remainingHours,0);});
test('dos fases 06 anticipación nunca desplaza una urgencia cuando no sobran horas',()=>{const today=[makeRow({productCode:'701',prepa:5,solde:-5}),makeRow({productCode:'702',prepa:5})],result=demandResult({today,sales:[{productCode:'702',salesByPrice:{1:5}}],hours:.5});assert.deepEqual(result.lists[0].lines.map(row=>[row.productCode,row.assignedQuantity]),[['701',5]]);});
test('dos fases 07 simples normales siguen sin anticipación por ventas',()=>{const today=[makeRow({productCode:'800',prepa:10,category:'SIMPLES'})],result=demandResult({today,sales:[{productCode:'800',salesByPrice:{1:10}}]});assert.equal(result.lists[0].lines.length,0);});
test('dos fases 08 rosas anticipan sin consumir la reserva',()=>{const today=[makeRow({productCode:'810',prepa:10,category:'ROSAS'})],result=demandResult({today,sales:[{productCode:'810',salesByPrice:{1:20}}]});assert.equal(result.lists[0].lines[0].assignedQuantity,8);assert.equal(result.availablePrepa['810-1'],2);});
test('dos fases 09 32486 anticipa como rosa y conserva reserva',()=>{const today=[makeRow({productCode:'32486',prepa:10,category:'SIMPLES'})],result=demandResult({today,sales:[{productCode:'32486',salesByPrice:{1:20}}]});assert.equal(result.lists[0].lines[0].assignedQuantity,8);assert.equal(result.availablePrepa['32486-1'],2);});
test('dos fases 10 compuestos pueden anticipar hasta consumir todo el Prepa',()=>{const today=[makeRow({productCode:'820',prepa:10})],result=demandResult({today,sales:[{productCode:'820',salesByPrice:{1:20}}]});assert.equal(result.lists[0].lines[0].assignedQuantity,10);assert.equal(result.availablePrepa['820-1'],0);});
test('sustitución 11 compuesto sin Prepa en P2 selecciona otro nivel de la familia',()=>{const today=compoundFamily(),normalized=M.normalizeManufacturingInputs({todayRecapRows:today,nomenclatures:[{productCode:'9000',category:'COMPUESTOS',manufacturingRates:[10,10,10]}]});assert.equal(normalized.rows.filter(row=>row.familyDemandSignal>0).length,1);assert.deepEqual(normalized.rows.find(row=>row.familyDemandSignal>0).alternativeForLevels,[2]);});
test('sustitución 12 nunca transfiere demanda a otro productCode',()=>{const today=[...compoundFamily(),makeRow({productCode:'9999',priceLevel:1,prepa:20,category:'COMPUESTOS'})],normalized=M.normalizeManufacturingInputs({todayRecapRows:today,nomenclatures:[{productCode:'9000',category:'COMPUESTOS',manufacturingRates:[10,10,10]},{productCode:'9999',category:'COMPUESTOS',manufacturingRates:[10]}]});assert.equal(normalized.rows.find(row=>row.productCode==='9999').familyDemandSignal,undefined);});
test('sustitución 13 entre P1 y P3 favorece el nivel con mayores ventas',()=>{const today=compoundFamily(),normalized=M.normalizeManufacturingInputs({todayRecapRows:today,salesRows:[{productCode:'9000',salesByPrice:{1:2,2:0,3:7}}],salesPeriodDays:1,nomenclatures:[{productCode:'9000',category:'COMPUESTOS',manufacturingRates:[10,10,10]}]});assert.equal(normalized.rows.find(row=>row.familyDemandSignal>0).priceLevel,3);});
test('sustitución 14 sin ventas usa necesidad propia y Prepa como criterio estable',()=>{const today=compoundFamily(),multi=[makeRow({productCode:'9000',priceLevel:1,prepa:0,solde:-1}),makeRow({productCode:'9000',priceLevel:2,prepa:0,solde:-2}),makeRow({productCode:'9000',priceLevel:3,prepa:0,solde:0})],normalized=M.normalizeManufacturingInputs({todayRecapRows:today,multiDayRecapRows:multi,nomenclatures:[{productCode:'9000',category:'COMPUESTOS',manufacturingRates:[10,10,10]}]});assert.equal(normalized.rows.find(row=>row.familyDemandSignal>0).priceLevel,1);});
test('sustitución 15 el nivel alternativo nunca supera su Prepa',()=>{const today=compoundFamily(),result=demandResult({today,hours:20});const alternative=result.lists[0].lines.find(row=>row.familyDemandSignal>0);assert.ok(alternative.assignedQuantity<=alternative.prepa);});
test('sustitución 16 señal P2 y ventas del alternativo se combinan con max, no suma',()=>{const today=compoundFamily().map(row=>row.priceLevel===2?{...row,solde:-5}:row),normalized=M.normalizeManufacturingInputs({todayRecapRows:today,salesRows:[{productCode:'9000',salesByPrice:{1:0,2:0,3:3}}],salesPeriodDays:1,nomenclatures:[{productCode:'9000',category:'COMPUESTOS',manufacturingRates:[10,10,10]}]}),alternative=normalized.rows.find(row=>row.familyDemandSignal>0);assert.equal(alternative.familyDemandSignal,5);assert.equal(alternative.salesSuggestedQuantity,3);assert.equal(alternative.additionalRecommended,5);});
test('sustitución 17 solo se aplica a COMPUESTOS',()=>{const today=compoundFamily().map(row=>({...row,category:'ROSAS'})),normalized=M.normalizeManufacturingInputs({todayRecapRows:today,nomenclatures:[{productCode:'9000',category:'ROSAS',manufacturingRates:[10,10,10]}]});assert.ok(normalized.rows.every(row=>row.familyDemandSignal===undefined));});
test('sustitución 18 ROSAS no cambian automáticamente de nivel',()=>{const today=compoundFamily().map(row=>({...row,category:'ROSAS'})),result=demandResult({today,nomenclatures:[{productCode:'9000',category:'ROSAS',manufacturingRates:[10,10,10]}]});assert.equal(result.lists[0].lines.length,0);});
test('sustitución 19 SIMPLES no cambian automáticamente de nivel',()=>{const today=compoundFamily().map(row=>({...row,category:'SIMPLES'})),result=demandResult({today,nomenclatures:[{productCode:'9000',category:'SIMPLES',manufacturingRates:[10,10,10]}]});assert.equal(result.lists[0].lines.length,0);});
test('sustitución 20 el PDF imprime el nivel alternativo real',()=>{const today=compoundFamily(),result=demandResult({today,sales:[{productCode:'9000',salesByPrice:{1:2,2:0,3:7}}]}),line=M.buildManufacturingPrintModel(result).pages[0].groups.flatMap(group=>group.lines).find(item=>item.level.startsWith('P3'));assert.ok(line);assert.equal(line.priorityToday,0);});

const weightedProposal=({salesA=8,salesB=2,hours=10,futureA=0,futureB=0}={})=>{const today=[makeRow({productCode:'9101',reference:'A',prepa:20}),makeRow({productCode:'9102',reference:'B',prepa:20})],multi=[futureA&&makeRow({productCode:'9101',reference:'A',solde:-futureA}),futureB&&makeRow({productCode:'9102',reference:'B',solde:-futureB})].filter(Boolean),result=demandResult({today,multi,sales:[{productCode:'9101',salesByPrice:{1:salesA}},{productCode:'9102',salesByPrice:{1:salesB}}],hours,nomenclatures:[{productCode:'9101',category:'COMPUESTOS',manufacturingRates:[1]},{productCode:'9102',category:'COMPUESTOS',manufacturingRates:[1]}]});return Object.fromEntries(result.lists.flatMap(list=>list.lines).map(line=>[line.productCode,line.assignedQuantity]));};
test('final 01 ventas 8 frente a 2 asignan claramente más al primero',()=>{const quantities=weightedProposal();assert.ok(quantities['9101']>quantities['9102']);});
test('final 02 capacidad 10 y ventas 8/2 se aproxima a 8/2',()=>{const quantities=weightedProposal();assert.deepEqual(quantities,{9101:8,9102:2});});
test('final 03 invertir ventas 2/8 invierte la preferencia',()=>{const quantities=weightedProposal({salesA:2,salesB:8});assert.deepEqual(quantities,{9102:8,9101:2});});
test('final 04 puede superar ceil dailySales en rondas posteriores',()=>{const today=[makeRow({productCode:'9201',prepa:10})],result=demandResult({today,sales:[{productCode:'9201',salesByPrice:{1:1}}],hours:10,nomenclatures:[{productCode:'9201',category:'COMPUESTOS',manufacturingRates:[1]}]}),line=result.lists[0].lines[0];assert.equal(line.assignedQuantity,10);assert.ok(line.assignedQuantity>Math.ceil(line.dailySales));});
test('final 05 compuesto puede consumir todo el Prepa permitido',()=>{const today=[makeRow({productCode:'9202',prepa:7})],result=demandResult({today,sales:[{productCode:'9202',salesByPrice:{1:1}}],hours:7,nomenclatures:[{productCode:'9202',category:'COMPUESTOS',manufacturingRates:[1]}]});assert.equal(result.availablePrepa['9202-1'],0);});
test('final 06 rosa anticipada conserva la reserva',()=>{const today=[makeRow({productCode:'9203',prepa:10,category:'ROSAS'})],result=demandResult({today,sales:[{productCode:'9203',salesByPrice:{1:99}}],hours:20,nomenclatures:[{productCode:'9203',category:'ROSAS',manufacturingRates:[1]}]});assert.equal(result.lists[0].lines[0].additionalApplied,8);assert.equal(result.availablePrepa['9203-1'],2);});
test('final 07 32486 conserva la misma reserva que rosas',()=>{const today=[makeRow({productCode:'32486',prepa:10,category:'SIMPLES'})],result=demandResult({today,sales:[{productCode:'32486',salesByPrice:{1:99}}],hours:20,nomenclatures:[{productCode:'32486',category:'SIMPLES',manufacturingRates:[1]}]});assert.equal(result.lists[0].lines[0].additionalApplied,8);assert.equal(result.availablePrepa['32486-1'],2);});
test('final 08 simple normal no anticipa aunque sea el más vendido',()=>{const today=[makeRow({productCode:'9204',prepa:20,category:'SIMPLES'}),makeRow({productCode:'9205',prepa:20})],result=demandResult({today,sales:[{productCode:'9204',salesByPrice:{1:1000}},{productCode:'9205',salesByPrice:{1:1}}],hours:10,nomenclatures:[{productCode:'9204',category:'SIMPLES',manufacturingRates:[1]},{productCode:'9205',category:'COMPUESTOS',manufacturingRates:[1]}]});assert.equal(result.lists[0].lines.some(line=>line.productCode==='9204'),false);});
test('final 09 urgencias siguen antes que cualquier anticipación',()=>{const today=[makeRow({productCode:'9206',prepa:5,solde:-5}),makeRow({productCode:'9207',prepa:20})],result=demandResult({today,sales:[{productCode:'9207',salesByPrice:{1:100}}],hours:5,nomenclatures:[{productCode:'9206',category:'COMPUESTOS',manufacturingRates:[1]},{productCode:'9207',category:'COMPUESTOS',manufacturingRates:[1]}]});assert.deepEqual(result.lists[0].lines.map(line=>[line.productCode,line.assignedQuantity]),[['9206',5]]);});
test('final 10 déficit futuro fuerte prevalece sobre ventas algo mayores',()=>{const quantities=weightedProposal({salesA:4,salesB:5,hours:6,futureA:8});assert.ok(quantities['9101']>quantities['9102']);});
test('final 11 limpiar recap hoy apunta solo a su texto y textarea',()=>{const source=htmlSource().match(/function clearManufacturingInput\(kind\)\{[^\n]+/)?.[0]||'';assert.match(source,/todayRecap:\{state:'todayRecapText',input:'manufacturingTodayRecapInput'\}/);});
test('final 12 limpiar recap varios días apunta solo a su bloque',()=>{const source=htmlSource().match(/function clearManufacturingInput\(kind\)\{[^\n]+/)?.[0]||'';assert.match(source,/multiDayRecap:\{state:'multiDayRecapText',input:'manufacturingMultiDayRecapInput'\}/);});
test('final 13 limpiar ventas apunta solo a ventas',()=>{const source=htmlSource().match(/function clearManufacturingInput\(kind\)\{[^\n]+/)?.[0]||'';assert.match(source,/sales:\{state:'salesText',input:'manufacturingSalesInput'\}/);});
test('final 14 limpiar elimina la validación correspondiente',()=>{const source=htmlSource().match(/function clearManufacturingInput\(kind\)\{[^\n]+/)?.[0]||'';assert.match(source,/invalidateManufacturingInput\(kind\)/);assert.match(htmlSource(),/validation\[kind\]='pending'/);});
test('final 15 limpiar conserva los otros textos y validaciones',()=>{const source=htmlSource().match(/function clearManufacturingInput\(kind\)\{[^\n]+/)?.[0]||'';assert.match(source,/manufacturingListState\[field\.state\]=''/);assert.doesNotMatch(source,/todayRecapText=''.*multiDayRecapText=''/);assert.match(source,/saveState\(\)/);});
test('final 16 limpiar invalida una propuesta anterior',()=>{const source=htmlSource().match(/function invalidateManufacturingInput\(kind\)\{[^\n]+/)?.[0]||'';assert.match(source,/result=null/);assert.match(source,/automaticResult=null/);assert.match(source,/modifications=\[\]/);});
test('final 17 prioridad positiva añade fondo gris a toda la fila',()=>{const source=htmlSource();assert.match(source,/manufacturing-priority-row>td\{background:#e7e7e7\}/);assert.match(source,/<tr class="\$\{line\.priorityToday>0\?'manufacturing-priority-row':''\}"/);});
test('final 18 prioridad cero no añade el destacado de fila',()=>{const source=htmlSource().match(/function renderManufacturingListsV3\(\)\{[^\n]+/)?.[0]||'';assert.match(source,/line\.priorityToday>0\?'manufacturing-priority-row':''/);});
test('final 19 PDF destaca toda la fila de prioridad',()=>{const source=htmlSource().match(/function printManufacturingLists\(floristId=null\)\{[\s\S]*?function productionDayOptions/)?.[0]||'';assert.match(source,/<tr class="\$\{line\.priorityToday>0\?'priority-row':''\}"/);assert.match(source,/\.priority-row td\{background:#e7e7e7/);});
test('final 20 PDF mantiene Hecho vacío',()=>{const source=htmlSource().match(/function printManufacturingLists\(floristId=null\)\{[\s\S]*?function productionDayOptions/)?.[0]||'';assert.match(source,/<td class="done"><\/td>/);});

test('claridad 01 PDF aplica gris a la fila cuando priorityToday es positivo',()=>{const source=htmlSource().match(/function printManufacturingLists\(floristId=null\)\{[\s\S]*?function productionDayOptions/)?.[0]||'';assert.match(source,/line\.priorityToday>0\?'priority-row':''/);assert.match(source,/\.priority-row td\{background:#e7e7e7/);});
test('claridad 02 PDF deja normal la fila con prioridad cero',()=>{const source=htmlSource().match(/function printManufacturingLists\(floristId=null\)\{[\s\S]*?function productionDayOptions/)?.[0]||'';assert.match(source,/priorityToday>0\?'priority-row':''/);assert.doesNotMatch(source,/priorityToday===0\?'priority-row'/);});
test('claridad 03 pantalla aplica gris a todas las celdas de la fila',()=>{const source=htmlSource().match(/function renderManufacturingListsV3\(\)\{[^\n]+/)?.[0]||'';assert.match(source,/<tr class="\$\{line\.priorityToday>0\?'manufacturing-priority-row':''\}"/);assert.match(htmlSource(),/\.manufacturing-priority-row>td\{background:#e7e7e7\}/);});
test('claridad 04 urgencias se insertan antes que avisos',()=>{const source=htmlSource().match(/function renderManufacturingLists\(\)\{[^\n]+/)?.[0]||'',assignment=source.match(/pending\.innerHTML=`([^`]+)`/)?.[1]||'';assert.ok(assignment.indexOf('${urgencyHtml}')<assignment.indexOf('${noticesHtml}'));});
test('claridad 05 una urgencia no cubierta no se duplica en warnings',()=>{const result=M.generateManufacturingLists({todayRecapRows:[makeRow({productCode:'9301',prepa:2,solde:-3})],florists:[{hours:10}],nomenclatures:[{productCode:'9301',category:'COMPUESTOS',manufacturingRates:[1]}]});assert.equal(M.manufacturingUrgencies(result).length,1);assert.ok(result.warnings.every(message=>!/urgencia/i.test(message)));});
test('claridad 06 texto operativo contiene necesidad fabricables y falta',()=>{const source=htmlSource().match(/function renderManufacturingLists\(\)\{[^\n]+/)?.[0]||'';assert.match(source,/Necesidad hoy/);assert.match(source,/Fabricables/);assert.match(source,/FALTA/);});
test('claridad 07 venta sin cruce identifica código referencia y nivel',()=>{const summary=M.summarizeSalesWithoutRecap([{reasonCode:'NO_RECAP',productCode:'37006',reference:'C-AUTHENTIQUE',priceLevel:2}]);assert.equal(summary.items[0].label,'37006 · C-AUTHENTIQUE · P2');});
test('claridad 08 ventas sin cruce se agrupan y limitan a diez',()=>{const rows=Array.from({length:12},(_,index)=>({reasonCode:'NO_RECAP',productCode:String(9400+index),reference:`Ramo ${index+1}`,priceLevel:index%4+1})),summary=M.summarizeSalesWithoutRecap(rows,10);assert.equal(summary.count,12);assert.equal(summary.items.length,10);assert.equal(summary.remaining,2);});
test('claridad 09 no se renderizan líneas genéricas repetidas de ventas',()=>{const source=htmlSource().match(/function renderManufacturingLists\(\)\{[^\n]+/)?.[0]||'';assert.equal((source.match(/Ventas sin cruce con recap de hoy/g)||[]).length,1);assert.doesNotMatch(source,/Ventas sin cruce con el recap de hoy\./);});
test('claridad 10 avisos excluyen claves ya presentes en urgencias',()=>{const source=htmlSource().match(/function renderManufacturingLists\(\)\{[^\n]+/)?.[0]||'';assert.match(source,/urgentKeys=new Set/);assert.match(source,/!urgentKeys\.has\(row\.key\)/);});

const unmatchedSales=(items)=>M.normalizeManufacturingInputs({todayRecapRows:[],salesRows:items.map((item,index)=>({productCode:item.productCode||String(9500+index),reference:item.reference,type:item.type||'Bouquet',salesByPrice:item.salesByPrice||{1:1}})),nomenclatures:items.map((item,index)=>({productCode:item.productCode||String(9500+index),category:item.category,manufacturingRates:[1],type:item.type||'Bouquet'}))}).salesWithoutRecap;
test('filtrado 01 X sin cruce no genera aviso',()=>assert.equal(unmatchedSales([{reference:'X-Rochers',category:'COMPUESTOS',salesByPrice:{2:1}}]).length,0));
test('filtrado 02 TF sin cruce no genera aviso',()=>assert.equal(unmatchedSales([{reference:'TF-Rosa-AQ004',category:'ROSAS'}]).length,0));
test('filtrado 03 SUSCRIPCION sin cruce no genera aviso',()=>assert.equal(unmatchedSales([{reference:'SUSCRIPCION-TAILLE-1',category:'SIMPLES'}]).length,0));
test('filtrado 04 S_zinc sin cruce no genera aviso',()=>assert.equal(unmatchedSales([{reference:'S_zinc pot 14cm',category:'SIMPLES'}]).length,0));
test('filtrado 05 S_ pot sin cruce no genera aviso',()=>assert.equal(unmatchedSales([{reference:'S_ pot_blanco_13cm',category:'SIMPLES'}]).length,0));
test('filtrado 06 compuesto válido sin cruce sí genera aviso',()=>assert.equal(unmatchedSales([{reference:'C-AUTHENTIQUE',category:'COMPUESTOS'}]).length,1));
test('filtrado 07 rosa válida sin cruce sí genera aviso',()=>assert.equal(unmatchedSales([{reference:'A-Rosas-Colores',category:'ROSAS',type:'Rose'}]).length,1));
test('filtrado 08 planta válida sin cruce sí genera aviso',()=>assert.equal(unmatchedSales([{reference:'P-Bonsai',category:'PLANTAS',type:'Plante'}]).length,1));
test('filtrado 09 simple válido sin cruce sí genera aviso',()=>assert.equal(unmatchedSales([{reference:'S-Alstro-parme',category:'SIMPLES'}]).length,1));
test('filtrado 10 categoría PENDIENTE no genera aviso',()=>assert.equal(unmatchedSales([{reference:'C-PENDIENTE',category:'PENDIENTE'}]).length,0));
test('filtrado 11 categoría desconocida no genera aviso',()=>assert.equal(unmatchedSales([{reference:'C-SIN-CATEGORIA'}]).length,0));
test('filtrado 12 contador incluye solo referencias relevantes',()=>{const rows=unmatchedSales([{reference:'X-Foto',category:'COMPUESTOS'},{reference:'TF-Blanco',category:'COMPUESTOS'},{reference:'C-VALIDO',category:'COMPUESTOS'},{reference:'A-VALIDA',category:'ROSAS',type:'Rose'}]),summary=M.summarizeSalesWithoutRecap(rows);assert.equal(summary.count,2);});
test('filtrado 13 si todos los casos están excluidos desaparece el aviso',()=>{const rows=unmatchedSales([{reference:'X-Foto',category:'COMPUESTOS'},{reference:'TF-Blanco',category:'COMPUESTOS'},{reference:'SUSCRIPCION-1',category:'SIMPLES'}]),summary=M.summarizeSalesWithoutRecap(rows);assert.equal(summary.count,0);assert.equal(summary.items.length,0);});
test('filtrado 14 límite diez y resto se calcula después del filtro',()=>{const valid=Array.from({length:12},(_,index)=>({reference:`C-VALIDO-${index}`,category:'COMPUESTOS'})),rows=unmatchedSales([{reference:'X-Foto',category:'COMPUESTOS'},...valid]),summary=M.summarizeSalesWithoutRecap(rows,10);assert.equal(summary.count,12);assert.equal(summary.items.length,10);assert.equal(summary.remaining,2);});
test('fila 01 el gris ya no se limita a la celda Prioridad hoy',()=>{const source=htmlSource();assert.doesNotMatch(source,/manufacturing-priority-highlight/);assert.match(source,/\.manufacturing-priority-row>td\{/);});
test('fila 02 el estilo de pantalla no cambia color ni peso de toda la fila',()=>{const rule=htmlSource().match(/\.manufacturing-priority-row>td\{[^}]+\}/)?.[0]||'';assert.doesNotMatch(rule,/color:/);assert.doesNotMatch(rule,/font-weight/);});
test('fila 03 PDF aplica la clase al tr completo',()=>{const source=htmlSource().match(/function printManufacturingLists\(floristId=null\)\{[\s\S]*?function productionDayOptions/)?.[0]||'';assert.match(source,/<tr class="\$\{line\.priorityToday>0\?'priority-row':''\}"/);assert.doesNotMatch(source,/class="\$\{line\.priorityToday>0\?'priority-row':''\}"[^>]*>\$\{productionNumber/);});
test('fila 04 PDF no cambia el color ni pone la fila en negrita',()=>{const source=htmlSource().match(/\.priority-row td\{[^}]+\}/)?.[0]||'';assert.doesNotMatch(source,/color:/);assert.doesNotMatch(source,/font-weight/);});
test('fila 05 PDF conserva print-color-adjust',()=>{const source=htmlSource().match(/\.priority-row td\{[^}]+\}/)?.[0]||'';assert.match(source,/-webkit-print-color-adjust:exact/);assert.match(source,/print-color-adjust:exact/);});
test('fila 06 el fondo no se aplica a toda la tabla',()=>{const source=htmlSource().match(/function printManufacturingLists\(floristId=null\)\{[\s\S]*?function productionDayOptions/)?.[0]||'';assert.doesNotMatch(source,/table td\{background:#e7e7e7/);assert.match(source,/\.priority-row td\{background:#e7e7e7/);});
