(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports) module.exports=api;
  if(root) root.AquarelleProduction=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';

  const PRODUCT_CATEGORIES=Object.freeze([
    {code:'ROSAS',label:'Rosas'},
    {code:'COMPUESTOS',label:'Ramos compuestos'},
    {code:'SIMPLES',label:'Ramos simples'},
    {code:'PLANTAS',label:'Plantas'}
  ]);
  const WEEK_DAYS=Object.freeze([
    {code:'monday',label:'Lunes',short:'Lun'},
    {code:'tuesday',label:'Martes',short:'Mar'},
    {code:'wednesday',label:'Miércoles',short:'Mié'},
    {code:'thursday',label:'Jueves',short:'Jue'},
    {code:'friday',label:'Viernes',short:'Vie'},
    {code:'saturday',label:'Sábado',short:'Sáb'},
    {code:'sunday',label:'Domingo',short:'Dom'}
  ]);
  const PRODUCTION_DAYS=WEEK_DAYS;
  const PRODUCTION_STATE_VERSION=5;
  const DEFAULT_PRODUCTION_DISTRIBUTION=Object.freeze({monday:0.08,tuesday:0.17,wednesday:0.19,thursday:0.20,friday:0.25,saturday:0.11,sunday:0});
  const TASK_TYPES=Object.freeze({MAIN:'principal',SATELLITE:'satelite'});
  const TASK_PRIORITIES=Object.freeze(['Baja','Media','Alta']);
  const TASK_MOBILITIES=Object.freeze(['Fija','Flexible']);
  const CALCULATION_TYPES=Object.freeze({QUANTITY:'por_cantidad',FIXED:'tiempo_fijo',SPECIAL:'especial',PERFORMANCE:'por_cantidad',FIXED_DURATION:'tiempo_fijo'});
  const WEEK_STATUSES=Object.freeze({DRAFT:'draft',VALIDATED:'validated'});
  const SPECIAL_TASK_DEFINITIONS=Object.freeze([
    {id:'production-main-reception',code:'RECEPTION',name:'Recepción',specialKind:'reception',rateMode:'category'},
    {id:'production-main-preassignment',code:'PREASSIGNMENT',name:'Preasignación',specialKind:'preassignment',rateMode:'category'},
    {id:'production-main-manufacturing',code:'MANUFACTURING',name:'Fabricación',specialKind:'manufacturing',rateMode:'variant'},
    {id:'production-main-shipping',code:'SHIPPING',name:'Expedición',specialKind:'shipping',rateMode:'global'}
  ]);
  const MAIN_TASK_DEFINITIONS=SPECIAL_TASK_DEFINITIONS;
  const DEFAULT_SATELLITE_TASKS=Object.freeze([
    {id:'production-satellite-pot-filling',code:'POT_FILLING',name:'Relleno de pots',frequency:'Bajo demanda'},
    {id:'production-satellite-monthly-inventory',code:'MONTHLY_INVENTORY',name:'Inventario mensual',frequency:'Mensual'},
    {id:'production-satellite-cold-room-stock',code:'COLD_ROOM_REAL_STOCK',name:'Control stock real en cámara',frequency:'Diaria'},
    {id:'production-satellite-cleaning',code:'CLEANING',name:'Limpieza',frequency:'Semanal'},
    {id:'production-satellite-plant-care',code:'PLANT_CARE',name:'Cuidado de plantas',frequency:'Semanal'},
    {id:'production-satellite-forklift-maintenance',code:'FORKLIFT_MAINTENANCE',name:'Mantenimiento de toro',frequency:'Bajo demanda'}
  ]);
  const RECENT_WEEKS_WEIGHT=0.60;
  const REFERENCE_WEEK_WEIGHT=0.40;
  const RECENT_VALID_WEEKS_COUNT=4;
  const DEFAULT_DISTRIBUTION_SETTINGS=Object.freeze({recentWeights:[1,1,1,1],recentShare:RECENT_WEEKS_WEIGHT*100,comparableShare:REFERENCE_WEEK_WEIGHT*100,maxRecentWeeks:RECENT_VALID_WEEKS_COUNT});
  const SPECIAL_BY_CODE=new Map(SPECIAL_TASK_DEFINITIONS.map(task=>[task.code,task]));

  function cleanText(value){return String(value==null?'':value).trim();}
  function isoNow(now){const date=now instanceof Date?now:new Date(now||Date.now());return Number.isNaN(date.getTime())?new Date().toISOString():date.toISOString();}
  function finiteNumber(value,fallback=0){if(value===''||value===null||value===undefined)return fallback;const number=Number(String(value).replace(',','.'));return Number.isFinite(number)?number:fallback;}
  function nonNegativeNumber(value,fallback=null){if(value===''||value===null||value===undefined)return fallback;const number=Number(String(value).replace(',','.'));return Number.isFinite(number)&&number>=0?number:fallback;}
  function positiveNumber(value){const number=nonNegativeNumber(value,null);return number!==null&&number>0?number:null;}
  function normalizeCode(value){return cleanText(value).toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Z0-9]+/g,'_').replace(/^_+|_+$/g,'');}
  function normalizeName(value){return cleanText(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
  function createId(prefix='production'){if(typeof crypto!=='undefined'&&crypto.randomUUID)return `${prefix}-${crypto.randomUUID()}`;return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`;}
  function clone(value){return JSON.parse(JSON.stringify(value));}
  function sameValue(left,right){return (left==null?null:left)===(right==null?null:right);}
  function normalizePriority(value){const text=normalizeName(value);return text==='baja'?'Baja':text==='alta'?'Alta':'Media';}
  function normalizeMobility(value){return normalizeName(value)==='fija'?'Fija':'Flexible';}
  function normalizeTaskType(value){return normalizeName(value)==='principal'?TASK_TYPES.MAIN:TASK_TYPES.SATELLITE;}
  function normalizeCalculationType(value){return ['rendimiento','por_cantidad'].includes(normalizeName(value))?CALCULATION_TYPES.QUANTITY:CALCULATION_TYPES.FIXED;}
  function validDay(value,allowAutomatic=false){const day=cleanText(value).toLowerCase();if(allowAutomatic&&day==='automatic')return day;return WEEK_DAYS.some(item=>item.code===day)?day:'';}
  function emptyDayValues(value=0){return Object.fromEntries(WEEK_DAYS.map(day=>[day.code,value]));}
  function emptyCategoryRates(){return Object.fromEntries(PRODUCT_CATEGORIES.map(category=>[category.code,{reception:null,preassignment:null}]));}
  function normalizeCategoryRates(input={}){const result=emptyCategoryRates();PRODUCT_CATEGORIES.forEach(category=>{const source=input?.[category.code]||{};result[category.code]={reception:positiveNumber(source.reception),preassignment:positiveNumber(source.preassignment)};});return result;}
  function normalizeManufacturingRates(values,count){const length=Math.max(1,parseInt(count,10)||1);return Array.from({length},(_,index)=>positiveNumber(Array.isArray(values)?values[index]:null));}

  function specialDefinition(input={}){return SPECIAL_BY_CODE.get(normalizeCode(input.code||input.specialKind||input.name))||SPECIAL_TASK_DEFINITIONS.find(item=>item.specialKind===cleanText(input.specialKind).toLowerCase())||null;}
  function normalizeTask(input={},options={}){
    const special=specialDefinition(input);
    const calculationType=special?CALCULATION_TYPES.SPECIAL:normalizeCalculationType(input.calculationType);
    const legacyPeople=Math.max(1,parseInt(input.peopleCount,10)||1);
    const rawDuration=input.durationHours??input.performanceOrDuration;
    const duration=normalizeName(input.calculationType)==='duracion_personas'&&positiveNumber(rawDuration)!=null?positiveNumber(rawDuration)*legacyPeople:positiveNumber(rawDuration);
    const name=cleanText(input.name)||special?.name||'';
    return {
      id:cleanText(input.id)||special?.id||createId('production-task'),
      code:normalizeCode(input.code||special?.code||name),
      name,
      type:normalizeTaskType(input.type??(special?TASK_TYPES.MAIN:TASK_TYPES.SATELLITE)),
      specialKind:special?.specialKind||'',
      rateMode:special?.rateMode||'',
      active:input.active!==false,
      calculationType,
      performance:calculationType===CALCULATION_TYPES.QUANTITY?positiveNumber(input.performance??input.performanceOrDuration):null,
      durationHours:calculationType===CALCULATION_TYPES.FIXED?duration:null,
      frequency:cleanText(input.frequency),
      priority:normalizePriority(input.priority),
      mobility:normalizeMobility(input.mobility),
      notes:cleanText(input.notes),
      createdAt:cleanText(input.createdAt)||isoNow(options.now),
      updatedAt:cleanText(input.updatedAt)||isoNow(options.now),
      ...(input.usageCount==null?{}:{usageCount:Math.max(0,parseInt(input.usageCount,10)||0)})
    };
  }
  function seedTasks(now){return [
    ...SPECIAL_TASK_DEFINITIONS.map(task=>normalizeTask({...task,type:TASK_TYPES.MAIN,active:true,priority:'Media',mobility:'Flexible'},{now})),
    ...DEFAULT_SATELLITE_TASKS.map(task=>normalizeTask({...task,type:TASK_TYPES.SATELLITE,active:true,calculationType:CALCULATION_TYPES.FIXED,priority:'Media',mobility:'Flexible'},{now}))
  ];}
  function migrateTasks(source={},options={}){
    if(Array.isArray(source.tasks)&&Number(source.version)>=4) return source.tasks.map(task=>normalizeTask(task,options));
    const result=[];
    SPECIAL_TASK_DEFINITIONS.forEach(definition=>{
      const objectSource=source.mainTasks&&!Array.isArray(source.mainTasks)?source.mainTasks[definition.code]:null;
      const arraySource=(Array.isArray(source.mainTasks)?source.mainTasks:[]).find(task=>normalizeCode(task.code)===definition.code);
      const legacySource=(Array.isArray(source.tasks)?source.tasks:[]).find(task=>normalizeCode(task.code)===definition.code);
      result.push(normalizeTask({...definition,...(objectSource||arraySource||legacySource||{}),id:definition.id,type:TASK_TYPES.MAIN},options));
    });
    let general=[];
    if(Array.isArray(source.satelliteTasks)) general=source.satelliteTasks;
    else if(Array.isArray(source.tasks)) general=source.tasks.filter(task=>!SPECIAL_BY_CODE.has(normalizeCode(task.code)));
    else general=DEFAULT_SATELLITE_TASKS.map(task=>({...task,type:TASK_TYPES.SATELLITE,calculationType:CALCULATION_TYPES.FIXED,active:true}));
    general.forEach(task=>result.push(normalizeTask({...task,type:task.type||TASK_TYPES.SATELLITE},options)));
    return result;
  }
  function deduplicateTasks(tasks){const ids=new Set(),codes=new Set();return tasks.filter(task=>task.id&&task.code&&!ids.has(task.id)&&!codes.has(task.code)&&ids.add(task.id)&&codes.add(task.code));}
  function ensureSpecialTasks(tasks,options={}){const result=tasks.slice();SPECIAL_TASK_DEFINITIONS.forEach(definition=>{if(!result.some(task=>task.code===definition.code))result.unshift(normalizeTask({...definition,type:TASK_TYPES.MAIN,active:true},options));});return result;}
  function normalizeChangeEntry(input={},options={}){return {id:cleanText(input.id)||createId('production-change'),scope:'task',entityKey:cleanText(input.entityKey),field:cleanText(input.field),changedAt:cleanText(input.changedAt)||isoNow(options.now),previousValue:input.previousValue??null,newValue:input.newValue??null,comment:cleanText(input.comment)};}

  function weeklyPlanKey(year,week){const normalizedYear=Math.max(2000,Math.min(2200,parseInt(year,10)||new Date().getFullYear()));const normalizedWeek=Math.max(1,Math.min(53,parseInt(week,10)||1));return `${normalizedYear}-W${String(normalizedWeek).padStart(2,'0')}`;}
  function isoWeekInfo(dateInput=new Date()){const date=new Date(dateInput),utc=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())),day=utc.getUTCDay()||7;utc.setUTCDate(utc.getUTCDate()+4-day);const year=utc.getUTCFullYear(),yearStart=new Date(Date.UTC(year,0,1)),week=Math.ceil((((utc-yearStart)/86400000)+1)/7);return {year,week,key:weeklyPlanKey(year,week)};}
  function isoWeekStart(year,week){const jan4=new Date(Date.UTC(year,0,4)),day=jan4.getUTCDay()||7,monday=new Date(jan4);monday.setUTCDate(jan4.getUTCDate()-(day-1)+(week-1)*7);return monday;}
  function isoWeekRange(year,week){const start=isoWeekStart(year,week),end=new Date(start);end.setUTCDate(start.getUTCDate()+6);return {start:start.toISOString().slice(0,10),end:end.toISOString().slice(0,10)};}
  function shiftWeek(year,week,delta){const start=isoWeekStart(parseInt(year,10),parseInt(week,10));start.setUTCDate(start.getUTCDate()+(parseInt(delta,10)||0)*7);return isoWeekInfo(start);}
  function emptyCategoryMix(){return Object.fromEntries(WEEK_DAYS.map(day=>[day.code,Object.fromEntries(PRODUCT_CATEGORIES.map(category=>[category.code,0]))]));}
  function normalizeCategoryMix(input={}){const result=emptyCategoryMix();WEEK_DAYS.forEach(day=>PRODUCT_CATEGORIES.forEach(category=>{result[day.code][category.code]=nonNegativeNumber(input?.[day.code]?.[category.code],0);}));return result;}
  function normalizeDayAssignments(input={},fallbackSameDay=false){return Object.fromEntries(WEEK_DAYS.map(day=>[day.code,validDay(input?.[day.code])||(fallbackSameDay?day.code:'')]));}
  function normalizeVariantMix(input=[]){if(!Array.isArray(input))return [];return input.map(entry=>({id:cleanText(entry.id)||createId('production-variant-mix'),day:validDay(entry.day),productKey:cleanText(entry.productKey),productCode:cleanText(entry.productCode),productName:cleanText(entry.productName),variantKey:cleanText(entry.variantKey),variantName:cleanText(entry.variantName),units:nonNegativeNumber(entry.units,0)})).filter(entry=>entry.day&&entry.variantKey&&entry.units>0);}
  function emptyAssignmentDays(){return Object.fromEntries(WEEK_DAYS.map(day=>[day.code,{selected:false,quantity:null}]));}
  function normalizeAssignmentDays(input={},legacyDay='',legacyQuantity=null){const days=emptyAssignmentDays();WEEK_DAYS.forEach(day=>{const source=input?.[day.code];if(source&&typeof source==='object'){days[day.code]={selected:source.selected===true,quantity:nonNegativeNumber(source.quantity,null)};}});const day=validDay(legacyDay);if(day)days[day]={selected:true,quantity:nonNegativeNumber(legacyQuantity,null)};return days;}
  function normalizeAssignments(input=[]){if(!Array.isArray(input))return [];const seen=new Set();return input.map(entry=>{const taskId=cleanText(entry.taskId),automatic=entry.day==='automatic'||entry.automatic===true,days=normalizeAssignmentDays(entry.days,entry.day,entry.quantity);if(automatic&&!Object.values(days).some(item=>item.selected))days.monday={selected:true,quantity:nonNegativeNumber(entry.quantity,null)};return {taskId,days,automatic};}).filter(entry=>entry.taskId&&!seen.has(entry.taskId)&&seen.add(entry.taskId));}
  function normalizePercentages(input={}){const values=Object.fromEntries(WEEK_DAYS.map(day=>[day.code,Math.max(0,finiteNumber(input?.[day.code],0))])),sum=Object.values(values).reduce((a,b)=>a+b,0);return sum>0?Object.fromEntries(WEEK_DAYS.map(day=>[day.code,values[day.code]/sum*100])):values;}
  function normalizeDailyValues(input={}){return Object.fromEntries(WEEK_DAYS.map(day=>[day.code,Math.max(0,Math.round(nonNegativeNumber(input?.[day.code],0)))]));}
  function normalizeDistributionContext(input={}){return {campaigns:Array.isArray(input.campaigns)?input.campaigns.map(cleanText).filter(Boolean):[],holidayDays:Array.isArray(input.holidayDays)?input.holidayDays.map(day=>validDay(day)).filter(Boolean):[],productionHolidayDays:Array.isArray(input.productionHolidayDays)?input.productionHolidayDays.map(day=>validDay(day)).filter(Boolean):[],holidayDetails:Array.isArray(input.holidayDetails)?clone(input.holidayDetails):[],references:Array.isArray(input.references)?clone(input.references):[],excluded:Array.isArray(input.excluded)?clone(input.excluded):[],sourceDetails:input.sourceDetails&&typeof input.sourceDetails==='object'?clone(input.sourceDetails):{},roundingAdjustments:Array.isArray(input.roundingAdjustments)?clone(input.roundingAdjustments):[],warnings:Array.isArray(input.warnings)?input.warnings.map(cleanText).filter(Boolean):[],calculatedAt:cleanText(input.calculatedAt),method:cleanText(input.method),source:cleanText(input.source)};}
  function legacyDailyValues(input={}){const result=emptyDayValues(0);WEEK_DAYS.forEach(day=>{const entry=input?.dailyForecast?.[day.code]||{};result[day.code]=Math.max(0,Math.round((nonNegativeNumber(entry.system,0)||0)+finiteNumber(entry.adjustment,0)));});return result;}
  function totalDaily(values={}){return WEEK_DAYS.reduce((sum,day)=>sum+(nonNegativeNumber(values?.[day.code],0)||0),0);}
  function createDistribution(input={},fallbackDaily={}){const calculated=normalizeDailyValues(input.calculated||fallbackDaily),hasAdjusted=input.adjusted&&typeof input.adjusted==='object',adjusted=normalizeDailyValues(hasAdjusted?input.adjusted:calculated);return {calculated,adjusted,calculationSource:cleanText(input.calculationSource)||'default',calculatedAt:cleanText(input.calculatedAt)||null,percentages:normalizePercentages(input.percentages||calculated)};}
  function createWeeklyPlan(year,week,options={}){const key=weeklyPlanKey(year,week),[safeYear,safeWeek]=key.replace('-W','-').split('-').map(Number),distribution=createDistribution();return {key,year:safeYear,week:safeWeek,status:WEEK_STATUSES.DRAFT,annualForecast:null,productionAdjustment:0,distribution,dailyDistributionAuto:distribution.percentages,dailyExpeditions:distribution.adjusted,dailyManual:false,distributionContext:normalizeDistributionContext(),categoryMix:emptyCategoryMix(),variantMix:[],preassignmentDays:normalizeDayAssignments({},true),satelliteAssignments:[],principalAssignments:[],taskSnapshots:{},updatedAt:isoNow(options.now),validatedAt:null};}
  function normalizeWeeklyPlan(input={},options={}){
    const fallback=createWeeklyPlan(input.year,input.week,options),key=weeklyPlanKey(input.year??fallback.year,input.week??fallback.week),[year,week]=key.replace('-W','-').split('-').map(Number);
    const legacyDaily=legacyDailyValues(input),hasNewDaily=input.dailyExpeditions&&typeof input.dailyExpeditions==='object';
    const annualForecast=nonNegativeNumber(input.annualForecast,input.bouquetSystem??(totalDaily(legacyDaily)||null));
    const productionAdjustment=finiteNumber(input.productionAdjustment,input.bouquetAdjustment??0);
    const dailyExpeditions=normalizeDailyValues(hasNewDaily?input.dailyExpeditions:legacyDaily);
    const dailyDistributionAuto=normalizePercentages(input.dailyDistributionAuto||(totalDaily(dailyExpeditions)?Object.fromEntries(WEEK_DAYS.map(day=>[day.code,dailyExpeditions[day.code]])):{}));
    const distribution=createDistribution(input.distribution,{...dailyExpeditions});
    if(input.distribution&&totalDaily(distribution.adjusted)===0&&totalDaily(dailyExpeditions)>0){distribution.adjusted=dailyExpeditions;distribution.calculated=totalDaily(distribution.calculated)?distribution.calculated:dailyExpeditions;distribution.percentages=normalizePercentages(distribution.calculated);}
    if(!input.distribution){distribution.percentages=normalizePercentages(input.dailyDistributionAuto||dailyExpeditions);distribution.calculationSource=cleanText(input.distributionContext?.method)||'migrated';}
    return {key,year,week,status:input.status===WEEK_STATUSES.VALIDATED?WEEK_STATUSES.VALIDATED:WEEK_STATUSES.DRAFT,annualForecast,productionAdjustment,distribution,dailyDistributionAuto:distribution.percentages,dailyExpeditions:distribution.adjusted,dailyManual:input.dailyManual===true||(!hasNewDaily&&totalDaily(legacyDaily)>0),distributionContext:normalizeDistributionContext(input.distributionContext),categoryMix:normalizeCategoryMix(input.categoryMix),variantMix:normalizeVariantMix(input.variantMix),preassignmentDays:normalizeDayAssignments(input.preassignmentDays,true),satelliteAssignments:normalizeAssignments(input.satelliteAssignments),principalAssignments:normalizeAssignments(input.principalAssignments),taskSnapshots:input.taskSnapshots&&typeof input.taskSnapshots==='object'?clone(input.taskSnapshots):{},updatedAt:cleanText(input.updatedAt)||isoNow(options.now),validatedAt:input.status===WEEK_STATUSES.VALIDATED?(cleanText(input.validatedAt)||cleanText(input.updatedAt)||isoNow(options.now)):null};
  }
  function normalizeWeeklyPlans(input={},options={}){if(!input||typeof input!=='object')return {};const result={};Object.values(input).forEach(plan=>{const normalized=normalizeWeeklyPlan(plan,options);result[normalized.key]=normalized;});return result;}
  function createProductionState(input,options={}){const source=input&&typeof input==='object'?input:{},isCurrent=Number(source.version)>=PRODUCTION_STATE_VERSION;let tasks=deduplicateTasks(migrateTasks(source,options));if(!isCurrent)tasks=ensureSpecialTasks(tasks,options);const oldHistory=Array.isArray(source?.legacy?.timeHistory)?source.legacy.timeHistory:Array.isArray(source.timeHistory)?source.timeHistory:[];return {version:PRODUCTION_STATE_VERSION,tasks,deletedTasks:Array.isArray(source.deletedTasks)?source.deletedTasks.map(item=>({id:cleanText(item.id),code:normalizeCode(item.code),name:cleanText(item.name),specialKind:cleanText(item.specialKind),deletedAt:cleanText(item.deletedAt)||isoNow(options.now)})):[],categoryRates:normalizeCategoryRates(source.categoryRates),shippingRate:positiveNumber(source.shippingRate)||(Array.isArray(source.tasks)?positiveNumber(source.tasks.find(task=>normalizeCode(task.code)==='SHIPPING')?.performance):null),distributionSettings:{...DEFAULT_DISTRIBUTION_SETTINGS,...(source.distributionSettings||{}),recentWeights:Array.isArray(source.distributionSettings?.recentWeights)?source.distributionSettings.recentWeights.map(value=>Math.max(0,finiteNumber(value,0))).slice(0,8):DEFAULT_DISTRIBUTION_SETTINGS.recentWeights.slice()},weeklyPlans:normalizeWeeklyPlans(source.weeklyPlans,options),changeHistory:Array.isArray(source.changeHistory)?source.changeHistory.map(entry=>normalizeChangeEntry(entry,options)):[],updatedAt:cleanText(source.updatedAt)||isoNow(options.now),...(oldHistory.length?{legacy:{timeHistory:clone(oldHistory)}}:{})};}

  function validateTask(task,allTasks=[],ignoreId=''){const errors=[];if(!task.name)errors.push('El nombre es obligatorio.');if(!task.code)errors.push('No se ha podido generar la identidad de la tarea.');if(allTasks.some(other=>other.id!==ignoreId&&other.code===task.code))errors.push('Ya existe una tarea con ese nombre o identidad.');if(!task.specialKind&&task.calculationType===CALCULATION_TYPES.QUANTITY&&task.performance==null)errors.push('Indica un rendimiento mayor que cero.');if(!task.specialKind&&task.calculationType===CALCULATION_TYPES.FIXED&&task.durationHours==null)errors.push('Indica las horas-persona de la tarea.');return errors;}
  function appendChange(state,input,options={}){const entry=normalizeChangeEntry(input,options);return {...state,changeHistory:[...state.changeHistory,entry],updatedAt:entry.changedAt};}
  function addProductionTask(stateInput,input,options={}){const state=createProductionState(stateInput,options),task=normalizeTask({...input,id:input.id||createId('production-task'),code:input.code||normalizeCode(input.name)},{now:options.now}),errors=validateTask(task,state.tasks);if(errors.length)return {ok:false,errors,state};return {ok:true,task,state:{...state,tasks:[...state.tasks,task],updatedAt:isoNow(options.now)}};}
  function updateProductionTask(stateInput,taskId,patch={},options={}){const state=createProductionState(stateInput,options),index=state.tasks.findIndex(task=>task.id===taskId);if(index<0)return {ok:false,errors:['La tarea no existe.'],state};const previous=state.tasks[index],next=normalizeTask({...previous,...patch,id:previous.id,code:previous.code,specialKind:previous.specialKind,createdAt:previous.createdAt,updatedAt:isoNow(options.now)},{now:options.now}),errors=validateTask(next,state.tasks,taskId);if(errors.length)return {ok:false,errors,state};const tasks=state.tasks.slice();tasks[index]=next;let updated={...state,tasks,updatedAt:isoNow(options.now)};['name','type','active','calculationType','performance','durationHours','frequency','priority','mobility','notes'].forEach(field=>{if(!sameValue(previous[field],next[field]))updated=appendChange(updated,{entityKey:taskId,field,previousValue:previous[field],newValue:next[field],comment:options.comment},options);});return {ok:true,task:next,state:updated};}
  function updateMainTask(stateInput,taskCode,patch={},options={}){const state=createProductionState(stateInput,options),task=state.tasks.find(item=>item.code===normalizeCode(taskCode));return task?updateProductionTask(state,task.id,patch,options):{ok:false,errors:['La tarea principal no existe.'],state};}
  function updateCategoryRate(stateInput,categoryCode,operation,value,options={}){const state=createProductionState(stateInput,options),code=normalizeCode(categoryCode);if(!PRODUCT_CATEGORIES.some(category=>category.code===code))return {ok:false,errors:['La categoría de producto no existe.'],state};if(!['reception','preassignment'].includes(operation))return {ok:false,errors:['La operación no es válida.'],state};const raw=cleanText(value),next=positiveNumber(value);if(raw&&next==null)return {ok:false,errors:['El rendimiento debe ser un número mayor que cero.'],state};const previous=state.categoryRates[code][operation];if(sameValue(previous,next))return {ok:true,changed:false,state};const categoryRates={...state.categoryRates,[code]:{...state.categoryRates[code],[operation]:next}};return {ok:true,changed:true,state:appendChange({...state,categoryRates},{entityKey:`${operation}:${code}`,field:'performance',previousValue:previous,newValue:next,comment:options.comment},options)};}
  function updateShippingRate(stateInput,value,options={}){const state=createProductionState(stateInput,options),raw=cleanText(value),next=positiveNumber(value);if(raw&&next==null)return {ok:false,errors:['El rendimiento debe ser un número mayor que cero.'],state};if(sameValue(state.shippingRate,next))return {ok:true,changed:false,state};return {ok:true,changed:true,state:appendChange({...state,shippingRate:next},{entityKey:'SHIPPING',field:'performance',previousValue:state.shippingRate,newValue:next,comment:options.comment},options)};}
  function deactivateProductionTask(stateInput,taskId,options={}){return updateProductionTask(stateInput,taskId,{active:false},options);}
  function deleteProductionTask(stateInput,taskId,options={}){const state=createProductionState(stateInput,options),task=state.tasks.find(item=>item.id===taskId);if(!task)return {ok:false,errors:['La tarea no existe.'],state};const deletedAt=isoNow(options.now),weeklyPlans={...state.weeklyPlans};Object.keys(weeklyPlans).forEach(key=>{const plan=normalizeWeeklyPlan(weeklyPlans[key],options),used=[...plan.satelliteAssignments,...plan.principalAssignments].some(item=>item.taskId===taskId);if(used||plan.status===WEEK_STATUSES.VALIDATED)plan.taskSnapshots={...plan.taskSnapshots,[taskId]:{id:task.id,code:task.code,name:task.name,type:task.type,specialKind:task.specialKind}};plan.satelliteAssignments=plan.satelliteAssignments.filter(item=>item.taskId!==taskId);plan.principalAssignments=plan.principalAssignments.filter(item=>item.taskId!==taskId);weeklyPlans[key]=plan;});const deletedTasks=[...state.deletedTasks.filter(item=>item.id!==taskId),{id:task.id,code:task.code,name:task.name,specialKind:task.specialKind,deletedAt}];return {ok:true,deletedTask:task,state:appendChange({...state,tasks:state.tasks.filter(item=>item.id!==taskId),deletedTasks,weeklyPlans,updatedAt:deletedAt},{entityKey:taskId,field:'deleted',previousValue:false,newValue:true,comment:options.comment||`Eliminada ${task.name}`},{...options,now:deletedAt})};}
  function taskTimingText(task){if(task.specialKind==='reception'||task.specialKind==='preassignment')return 'Rendimiento por categoría';if(task.specialKind==='manufacturing')return 'Rendimiento por producto y variante';if(task.specialKind==='shipping')return 'Rendimiento global de expedición';if(task.calculationType===CALCULATION_TYPES.QUANTITY)return task.performance==null?'Pendiente':`${task.performance} uds/h/persona`;return task.durationHours==null?'Pendiente':`${task.durationHours} h-persona`;}
  function calculateTaskPersonHours(taskInput,workload=1){const task=normalizeTask(taskInput);if(task.specialKind)return null;if(task.calculationType===CALCULATION_TYPES.QUANTITY){const amount=nonNegativeNumber(workload,null);return amount==null||task.performance==null?null:amount/task.performance;}return task.durationHours;}
  function manufacturingTaskDescriptor(){return Object.freeze({code:'MANUFACTURING',name:'Fabricación',calculationType:CALCULATION_TYPES.QUANTITY,unit:'unidades / hora / persona',source:'nomenclatures',editable:false});}

  function weeklyTotalUsed(planInput){const plan=normalizeWeeklyPlan(planInput);return Math.max(0,Math.round((nonNegativeNumber(plan.annualForecast,0)||0)+finiteNumber(plan.productionAdjustment,0)));}
  function largestRemainder(total,weights={}){const rounded=Math.max(0,Math.round(finiteNumber(total,0))),clean=WEEK_DAYS.map(day=>Math.max(0,finiteNumber(weights?.[day.code],0))),sum=clean.reduce((a,b)=>a+b,0);if(!sum)return emptyDayValues(0);const raw=clean.map(value=>value/sum*rounded),values=raw.map(Math.floor);let left=rounded-values.reduce((a,b)=>a+b,0);raw.map((value,index)=>({index,remainder:value-values[index]})).sort((a,b)=>b.remainder-a.remainder||a.index-b.index).slice(0,left).forEach(item=>values[item.index]++);return Object.fromEntries(WEEK_DAYS.map((day,index)=>[day.code,values[index]]));}
  function dailyPercentages(values={}){const total=totalDaily(values);return total?Object.fromEntries(WEEK_DAYS.map(day=>[day.code,(nonNegativeNumber(values[day.code],0)||0)/total*100])):emptyDayValues(0);}
  function calculateProductionDailyProposal(input={}){const weeklyTotal=Math.max(0,Math.round(nonNegativeNumber(input.weeklyTotal,0)||0)),blocked=new Set((input.blockedDays||[]).map(day=>validDay(day)).filter(Boolean)),warnings=[];let weights=input.historicalPercentages&&Object.values(input.historicalPercentages).some(value=>positiveNumber(value)!=null)?input.historicalPercentages:(input.fallbackPercentages||DEFAULT_PRODUCTION_DISTRIBUTION),source=cleanText(input.source)||(weights===input.historicalPercentages?'saved':'default');const available=WEEK_DAYS.filter(day=>!blocked.has(day.code));if(weeklyTotal>0&&!available.length){warnings.push('No hay días operativos disponibles para repartir las expediciones.');return {days:emptyDayValues(0),percentages:emptyDayValues(0),source,warnings};}const filtered=Object.fromEntries(WEEK_DAYS.map(day=>[day.code,blocked.has(day.code)?0:Math.max(0,finiteNumber(weights?.[day.code],0))]));if(weeklyTotal>0&&!Object.values(filtered).some(Boolean)){available.forEach(day=>{filtered[day.code]=1;});warnings.push('Los porcentajes disponibles no eran válidos; se ha repartido entre los días operativos.');source='default';}const days=largestRemainder(weeklyTotal,filtered);blocked.forEach(day=>{days[day]=0;});return {days,percentages:dailyPercentages(days),source,warnings};}
  function distributionBalance(planInput){const plan=normalizeWeeklyPlan(planInput),used=weeklyTotalUsed(plan),daily=totalDaily(plan.distribution.adjusted);return {used,daily,difference:used-daily,percentages:dailyPercentages(plan.distribution.adjusted),calculatedTotal:totalDaily(plan.distribution.calculated),adjustedTotal:daily};}
  function applyDistributionProposal(planInput,proposal={},options={}){const plan=normalizeWeeklyPlan(planInput),calculated=normalizeDailyValues(proposal.days||proposal.dailyExpeditions||largestRemainder(weeklyTotalUsed(plan),proposal.percentages)),hadManual=plan.dailyManual===true||JSON.stringify(plan.distribution.adjusted)!==JSON.stringify(plan.distribution.calculated),replaceAdjusted=options.replaceAdjusted===true||(!hadManual&&options.preserveAdjusted!==true),adjusted=replaceAdjusted?calculated:plan.distribution.adjusted,percentages=normalizePercentages(proposal.percentages||calculated),calculatedAt=proposal.calculatedAt||isoNow();return normalizeWeeklyPlan({...plan,distribution:{calculated,adjusted,calculationSource:proposal.source||proposal.method||'default',calculatedAt,percentages},dailyDistributionAuto:percentages,dailyExpeditions:adjusted,dailyManual:replaceAdjusted?false:hadManual,distributionContext:{campaigns:proposal.campaigns||[],holidayDays:proposal.holidayDays||[],productionHolidayDays:proposal.productionHolidayDays||[],holidayDetails:proposal.holidayDetails||[],references:proposal.references||[],excluded:proposal.excluded||[],sourceDetails:proposal.sourceDetails||{},roundingAdjustments:proposal.roundingAdjustments||[],warnings:proposal.warnings||[],calculatedAt,method:proposal.method||proposal.source||'',source:proposal.source||''},status:WEEK_STATUSES.DRAFT,validatedAt:null});}
  function spreadDailyDifference(planInput){const plan=normalizeWeeklyPlan(planInput),balance=distributionBalance(plan);if(!balance.difference)return plan;const proposal=calculateProductionDailyProposal({weeklyTotal:balance.used,historicalPercentages:totalDaily(plan.distribution.adjusted)?plan.distribution.adjusted:plan.distribution.calculated,blockedDays:plan.distributionContext.holidayDays||[],fallbackPercentages:DEFAULT_PRODUCTION_DISTRIBUTION,source:plan.distribution.calculationSource});plan.distribution.adjusted=proposal.days;plan.dailyExpeditions=plan.distribution.adjusted;plan.dailyManual=true;plan.status=WEEK_STATUSES.DRAFT;plan.validatedAt=null;return plan;}
  function campaignNames(value){return (Array.isArray(value)?value:String(value||'').split(/\s*[·,]\s*/)).map(cleanText).filter(Boolean);}
  function normalizeHistoryWeek(input={}){const daily=normalizeDailyValues(input.daily||input.dailyExpeditions),total=totalDaily(daily);return {year:Number(input.year),week:Number(input.week),status:cleanText(input.status)||'closed',isComplete:input.isComplete===true,campaigns:campaignNames(input.campaigns||input.campaign),holidayDays:(input.holidayDays||input.holidays||[]).map(day=>validDay(day)).filter(Boolean),hasOperationalClosure:input.hasOperationalClosure===true||input.operationalClosure===true||(Array.isArray(input.closureDays)&&input.closureDays.length>0),hasAnomaly:input.hasAnomaly===true||input.hasIncident===true||input.incident===true,daily,total};}
  function historyInvalidReason(item){if(item.status!=='closed')return 'semana pendiente de cierre';if(!item.isComplete)return 'semana incompleta';if(item.total<=0)return 'sin expediciones reales válidas';if(item.campaigns.length)return 'campaña';if(item.holidayDays.length)return 'festivo';if(item.hasOperationalClosure)return 'cierre operativo';if(item.hasAnomaly)return 'días anómalos o incompletos';return '';}
  function averageHistoryPercentages(weeks){const result=emptyDayValues(0);if(!weeks.length)return result;weeks.forEach(item=>{const percentages=dailyPercentages(item.daily);WEEK_DAYS.forEach(day=>{result[day.code]+=percentages[day.code]/weeks.length;});});return normalizePercentages(result);}
  function percentageSnapshot(values){return Object.fromEntries(WEEK_DAYS.map(day=>[day.code,Number(finiteNumber(values?.[day.code],0).toFixed(4))]));}
  function roundingDetails(total,percentages,days){return WEEK_DAYS.map(day=>{const raw=Math.max(0,finiteNumber(percentages?.[day.code],0))*total/100,rounded=nonNegativeNumber(days?.[day.code],0)||0;return {day:day.code,raw:Number(raw.toFixed(4)),rounded,adjustment:Number((rounded-raw).toFixed(4))};});}
  function proposeDailyDistribution(input={}){
    const year=Number(input.year),week=Number(input.week),total=Math.max(0,Math.round(nonNegativeNumber(input.total,0)||0)),campaigns=campaignNames(input.campaigns),holidayDays=(input.holidayDays||[]).map(day=>validDay(day)).filter(Boolean),settings={...DEFAULT_DISTRIBUTION_SETTINGS,...(input.settings||{})},warnings=[],excluded=[];
    const history=(input.historyWeeks||[]).map(normalizeHistoryWeek).filter(item=>item.year&&item.week),maxRecent=Math.max(1,Math.round(finiteNumber(settings.maxRecentWeeks,RECENT_VALID_WEEKS_COUNT))),currentCandidates=history.filter(item=>item.year===year&&item.week<week).sort((a,b)=>b.week-a.week),validRecent=[];
    currentCandidates.forEach(item=>{const reason=historyInvalidReason(item);if(reason)excluded.push({year:item.year,week:item.week,reason});else if(validRecent.length<maxRecent)validRecent.push(item);});
    const comparableYear=Number(input.comparableYear),referenceCandidate=history.find(item=>item.year===comparableYear&&item.week===week)||null,referenceReason=referenceCandidate?historyInvalidReason(referenceCandidate):'semana no disponible',reference=referenceCandidate&&!referenceReason?referenceCandidate:null;
    if(referenceCandidate&&referenceReason)excluded.push({year:referenceCandidate.year,week:referenceCandidate.week,reason:referenceReason});
    const recentPercentages=averageHistoryPercentages(validRecent),referencePercentages=reference?dailyPercentages(reference.daily):emptyDayValues(0),hasRecent=validRecent.length>0,hasReference=!!reference;
    let recentShare=hasRecent?Math.max(0,finiteNumber(settings.recentShare,RECENT_WEEKS_WEIGHT*100)):0,referenceShare=hasReference?Math.max(0,finiteNumber(settings.comparableShare,REFERENCE_WEEK_WEIGHT*100)):0;
    if(hasRecent&&!hasReference){recentShare=100;referenceShare=0;warnings.push('La semana de referencia no está disponible; se usa el 100 % del histórico reciente.');}
    if(!hasRecent&&hasReference){recentShare=0;referenceShare=100;warnings.push('No hay semanas recientes válidas; se usa el 100 % de la semana de referencia.');}
    let sourceTotal=recentShare+referenceShare;if(sourceTotal<=0){recentShare=hasRecent?RECENT_WEEKS_WEIGHT*100:0;referenceShare=hasReference?REFERENCE_WEEK_WEIGHT*100:0;sourceTotal=recentShare+referenceShare;}const combined=emptyDayValues(0);
    if(sourceTotal>0)WEEK_DAYS.forEach(day=>{combined[day.code]=(recentPercentages[day.code]*recentShare+referencePercentages[day.code]*referenceShare)/sourceTotal;});
    if(!hasRecent&&!hasReference){warnings.push('No se encontró histórico válido: se ha aplicado la distribución estándar.');const fallback=calculateProductionDailyProposal({weeklyTotal:total,blockedDays:holidayDays,fallbackPercentages:input.fallbackPercentages||DEFAULT_PRODUCTION_DISTRIBUTION,source:'default'}),sourceDetails={recent:{weeks:[],percentages:emptyDayValues(0),weight:0},reference:{year:comparableYear||null,week,used:false,reason:referenceReason,percentages:emptyDayValues(0),weight:0},finalPercentages:percentageSnapshot(fallback.percentages)};return {year,week,total,campaigns,holidayDays,percentages:fallback.percentages,dailyExpeditions:fallback.days,days:fallback.days,source:'default',references:[],excluded,sourceDetails,roundingAdjustments:roundingDetails(total,fallback.percentages,fallback.days),warnings:[...warnings,...fallback.warnings],method:'Distribución estándar (fallback)',calculatedAt:isoNow(input.now)};}
    const normalized=normalizePercentages(combined),source=hasRecent&&hasReference?'recent-and-reference':hasRecent?'recent-average':'reference-week',proposal=calculateProductionDailyProposal({weeklyTotal:total,historicalPercentages:normalized,blockedDays:holidayDays,fallbackPercentages:DEFAULT_PRODUCTION_DISTRIBUTION,source}),references=[];
    validRecent.forEach(item=>references.push({year:item.year,week:item.week,weight:Number((recentShare/validRecent.length/sourceTotal*100).toFixed(2)),source:'recent',reason:'Semana reciente completa y limpia',percentages:percentageSnapshot(dailyPercentages(item.daily))}));
    if(reference)references.push({year:reference.year,week:reference.week,weight:Number((referenceShare/sourceTotal*100).toFixed(2)),source:'reference',reason:`Misma semana de ${comparableYear}`,percentages:percentageSnapshot(referencePercentages)});
    const sourceDetails={recent:{weeks:validRecent.map(item=>({year:item.year,week:item.week})),percentages:percentageSnapshot(recentPercentages),weight:Number((recentShare/sourceTotal*100).toFixed(2))},reference:{year:comparableYear||null,week,used:hasReference,reason:hasReference?'Semana equivalente completa y limpia':referenceReason,percentages:percentageSnapshot(referencePercentages),weight:Number((referenceShare/sourceTotal*100).toFixed(2))},finalPercentages:percentageSnapshot(normalized)};
    return {year,week,total,campaigns,holidayDays,percentages:proposal.percentages,dailyExpeditions:proposal.days,days:proposal.days,source,references,excluded,sourceDetails,roundingAdjustments:roundingDetails(total,normalized,proposal.days),warnings:[...warnings,...proposal.warnings],method:'Media de semanas recientes + semana equivalente de referencia',calculatedAt:isoNow(input.now)};
  }

  function purchaseQuantity(item){return nonNegativeNumber(item.units??item.quantity??item.amount??item.purchasedQuantity,0)||0;}
  function calculatePurchaseOperationHours({purchasesByDay,purchases,categoryPerformances,operation='preassignment'}={}){const flat=Array.isArray(purchases)?purchases:WEEK_DAYS.flatMap(day=>(Array.isArray(purchasesByDay?.[day.code])?purchasesByDay[day.code]:[]).map(item=>({...item,day:item.day||day.code}))),byDay=Object.fromEntries(WEEK_DAYS.map(day=>[day.code,{totalHours:0,purchasedQuantity:0,byCategory:{}}])),missingPerformances=[],warnings=[],missing=new Set();flat.forEach(item=>{const day=validDay(item.day),category=normalizeCode(item.category),quantity=purchaseQuantity(item);if(!day||!category||quantity<=0)return;const bucket=byDay[day];bucket.purchasedQuantity+=quantity;const rate=positiveNumber(categoryPerformances?.[category]?.[operation]??categoryPerformances?.[category]);if(rate==null){if(!missing.has(category)){missing.add(category);missingPerformances.push(category);}return;}const hours=quantity/rate;bucket.totalHours+=hours;bucket.byCategory[category]=(bucket.byCategory[category]||0)+hours;});if(!flat.some(item=>purchaseQuantity(item)>0))warnings.push('Sin compras previstas para esta semana');missingPerformances.forEach(category=>warnings.push(`Falta rendimiento de ${operation==='reception'?'recepción':'preasignación'} para ${PRODUCT_CATEGORIES.find(item=>item.code===category)?.label||category}`));return {byDay,weeklyTotal:WEEK_DAYS.reduce((sum,day)=>sum+byDay[day.code].totalHours,0),missingPerformances,warnings};}
  function calculateDailyPreassignmentHours(input={}){return calculatePurchaseOperationHours({...input,operation:'preassignment'});}
  function calculateDailyReceptionHours(input={}){return calculatePurchaseOperationHours({...input,operation:'reception'});}

  const MATERIAL_MANUFACTURING_GAP_PERCENT=5;
  function manufacturingKey(value){return normalizeCode(value).replace(/_/g,'');}
  function manufacturingWeekOrder(value){const year=Math.max(0,Math.round(finiteNumber(value?.year,0))),week=Math.max(0,Math.round(finiteNumber(value?.week,0)));return year*100+week;}
  function allocateIntegerTotal(total,weights=[]){const target=Math.max(0,Math.round(finiteNumber(total,0))),clean=weights.map(value=>Math.max(0,finiteNumber(value,0))),sum=clean.reduce((a,b)=>a+b,0);if(!clean.length)return [];if(!sum)return clean.map(()=>0);const raw=clean.map(value=>value/sum*target),allocated=raw.map(Math.floor);let remaining=target-allocated.reduce((a,b)=>a+b,0);raw.map((value,index)=>({index,remainder:value-allocated[index]})).sort((a,b)=>b.remainder-a.remainder||a.index-b.index).slice(0,remaining).forEach(item=>allocated[item.index]++);return allocated;}
  function normalizeManufacturingVariants(input=[]){return (Array.isArray(input)?input:[]).map((item,index)=>{const raw=Number(item?.quantity??item?.units??item?.forecastUnits??0);return {variantKey:cleanText(item?.variantKey??item?.variant??item?.priceLevel??item?.index??index+1)||String(index+1),variantName:cleanText(item?.variantName??item?.name)||`P${index+1}`,variantIndex:Math.max(1,Math.round(finiteNumber(item?.variantIndex??item?.index,index+1))),quantity:Number.isFinite(raw)?raw:0};});}
  function normalizeManufacturingProducts(input=[]){return (Array.isArray(input)?input:[]).map((item,index)=>{const raw=Number(item?.forecastUnits??item?.quantity??item?.units??0),productId=cleanText(item?.productId??item?.productCode??item?.code??item?.id??item?.name)||`product-${index+1}`;return {productId,productCode:cleanText(item?.productCode??item?.code??productId),name:cleanText(item?.name??item?.productName??item?.productReference??productId),category:normalizeCode(item?.category),forecastUnits:Number.isFinite(raw)?raw:0,daily:normalizeDailyValues(item?.daily||item?.dailyUnits),variants:normalizeManufacturingVariants(item?.variants)};});}
  function manufacturingHistoryValid(week){return week&&week.isComplete!==false&&cleanText(week.status||'closed')==='closed'&&!campaignNames(week.campaigns||week.campaign).length&&!(week.holidayDays||week.holidays||[]).length&&week.hasOperationalClosure!==true&&week.hasAnomaly!==true&&week.hasIncident!==true;}
  function manufacturingProductFromWeek(week,product){const products=normalizeManufacturingProducts(week?.products||week?.productForecast),key=manufacturingKey(product.productId||product.productCode);return products.find(item=>manufacturingKey(item.productId)===key||manufacturingKey(item.productCode)===key)||null;}
  function manufacturingVariantPercentages(product){const variants=product?.variants?.filter(item=>item.quantity>0)||[],total=variants.reduce((sum,item)=>sum+item.quantity,0);return total?Object.fromEntries(variants.map(item=>[String(item.variantIndex),item.quantity/total*100])):{};}
  function averageManufacturingVariantPercentages(weeks,product){const samples=weeks.map(week=>manufacturingProductFromWeek(week,product)).filter(Boolean).map(manufacturingVariantPercentages).filter(sample=>Object.keys(sample).length),keys=[...new Set(samples.flatMap(sample=>Object.keys(sample)))];return samples.length?Object.fromEntries(keys.map(key=>[key,samples.reduce((sum,sample)=>sum+(sample[key]||0),0)/samples.length])):{};}
  function averageManufacturingCategoryPercentages(weeks,category){const samples=[];(weeks||[]).forEach(week=>normalizeManufacturingProducts(week?.products||week?.productForecast).filter(product=>product.category===category).forEach(product=>{const sample=manufacturingVariantPercentages(product);if(Object.keys(sample).length)samples.push(sample);}));const keys=[...new Set(samples.flatMap(sample=>Object.keys(sample)))];return samples.length?Object.fromEntries(keys.map(key=>[key,samples.reduce((sum,sample)=>sum+(sample[key]||0),0)/samples.length])):{};}
  function manufacturingNomenclatureMap(input){const entries=Array.isArray(input)?input.map(item=>[item?.productId??item?.productCode??item?.code,item]):Object.entries(input&&typeof input==='object'?input:{}),map=new Map();entries.forEach(([key,item])=>{const productKey=manufacturingKey(item?.productId??item?.productCode??item?.code??key);if(!productKey)return;const array=Array.isArray(item?.manufacturingRates)?item.manufacturingRates:[],object=item?.variantRates&&typeof item.variantRates==='object'?item.variantRates:{};map.set(productKey,{productId:cleanText(item?.productId??item?.productCode??item?.code??key),category:normalizeCode(item?.category),rates:array.map(value=>positiveNumber(value)),variantRates:Object.fromEntries(Object.entries(object).map(([variant,value])=>[String(variant),positiveNumber(value)]))});});return map;}
  function calculateManufacturingPlan(input={}){
    const weeklyTotal=Math.max(0,Math.round(finiteNumber(input.weeklyTotal,0))),warnings=[],blockingErrors=[],negativeInputs=[],rawProducts=normalizeManufacturingProducts(input.productForecast);
    rawProducts.forEach(product=>{if(product.forecastUnits<0)negativeInputs.push(product.name);product.variants.forEach(variant=>{if(variant.quantity<0)negativeInputs.push(`${product.name} ${variant.variantName}`);});});
    if(negativeInputs.length)blockingErrors.push(`Hay cantidades negativas en Fabricación: ${[...new Set(negativeInputs)].join(', ')}.`);
    const products=rawProducts.filter(product=>product.forecastUnits>0),forecastTotal=products.reduce((sum,item)=>sum+item.forecastUnits,0),dailyHours=emptyDayValues(0),nomenclatures=manufacturingNomenclatureMap(input.nomenclatures),recent=(input.recentHistory||[]).filter(manufacturingHistoryValid).sort((a,b)=>manufacturingWeekOrder(b)-manufacturingWeekOrder(a)).slice(0,RECENT_VALID_WEEKS_COUNT),reference=manufacturingHistoryValid(input.referenceWeek)?input.referenceWeek:null;
    if(weeklyTotal>0&&!products.length){blockingErrors.push('No existe previsión por producto ni por categoría para calcular Fabricación.');return {weeklyHours:0,dailyHours,products:[],status:'pending',warnings,blockingErrors,calculationMeta:{recentWeeksUsed:[],referenceWeekUsed:null,exactPercentage:0,estimatedPercentage:0,unresolvedPercentage:100,forecastTotal:0,normalizedTotal:weeklyTotal}};}
    const normalizedTotals=forecastTotal&&weeklyTotal!==forecastTotal?allocateIntegerTotal(weeklyTotal,products.map(item=>item.forecastUnits)):products.map(item=>Math.max(0,Math.round(item.forecastUnits)));
    if(forecastTotal&&weeklyTotal!==forecastTotal)warnings.push(`La previsión por producto suma ${forecastTotal}; se ha normalizado proporcionalmente a ${weeklyTotal}.`);
    const categoryRates={};nomenclatures.forEach(item=>[...(item.rates||[]),...Object.values(item.variantRates||{})].forEach(rate=>{if(rate){const category=item.category||'SIN_CATEGORIA';(categoryRates[category]||(categoryRates[category]=[])).push(rate);}}));
    const savedVariants=normalizeManufacturingProducts(input.variantForecast),generalHistory=(input.generalHistory||[]).filter(manufacturingHistoryValid),recentWeeksUsed=new Map(),resultProducts=[];let exactUnits=0,estimatedUnits=0,unresolvedUnits=0,undistributedHours=0,referenceUsed=false;
    products.forEach((product,index)=>{
      const normalizedUnits=normalizedTotals[index],saved=savedVariants.find(item=>manufacturingKey(item.productId)===manufacturingKey(product.productId)||manufacturingKey(item.productCode)===manufacturingKey(product.productCode)),recentPct=averageManufacturingVariantPercentages(recent,product),referenceProduct=reference?manufacturingProductFromWeek(reference,product):null,referencePct=manufacturingVariantPercentages(referenceProduct),generalPct=averageManufacturingVariantPercentages(generalHistory,product),categoryPct=averageManufacturingCategoryPercentages(generalHistory,product.category);let variants=product.variants.filter(item=>item.quantity>0),variantSource='explicit-forecast',sourceLabel='Variante prevista';
      if(!variants.length&&saved?.variants.some(item=>item.quantity>0)){variants=saved.variants.filter(item=>item.quantity>0);variantSource='saved-week';sourceLabel='Distribución guardada';}
      if(!variants.length&&(Object.keys(recentPct).length||Object.keys(referencePct).length)){const keys=[...new Set([...Object.keys(recentPct),...Object.keys(referencePct)])],hasRecent=Object.keys(recentPct).length>0,hasReference=Object.keys(referencePct).length>0,recentWeight=hasRecent?(hasReference?RECENT_WEEKS_WEIGHT:1):0,referenceWeight=hasReference?(hasRecent?REFERENCE_WEEK_WEIGHT:1):0;variants=keys.map(key=>({variantKey:key,variantName:`P${key}`,variantIndex:Number(key)||1,quantity:(recentPct[key]||0)*recentWeight+(referencePct[key]||0)*referenceWeight}));variantSource=hasRecent&&hasReference?'recent-reference-blend':hasRecent?'recent-history':'reference-week';sourceLabel=hasRecent&&hasReference?'Histórico reciente + referencia':hasRecent?'Histórico reciente':'Semana de referencia';if(hasRecent)recent.forEach(week=>recentWeeksUsed.set(`${week.year}-${week.week}`,{year:Number(week.year),week:Number(week.week)}));if(hasReference)referenceUsed=true;warnings.push(`${product.name}: se ha utilizado ${sourceLabel.toLowerCase()} porque no existe detalle explícito por variante.`);}
      if(!variants.length&&Object.keys(generalPct).length){variants=Object.entries(generalPct).map(([key,quantity])=>({variantKey:key,variantName:`P${key}`,variantIndex:Number(key)||1,quantity}));variantSource='product-history';sourceLabel='Histórico general del producto';}
      if(!variants.length&&Object.keys(categoryPct).length){variants=Object.entries(categoryPct).map(([key,quantity])=>({variantKey:key,variantName:`P${key}`,variantIndex:Number(key)||1,quantity}));variantSource='category-average';sourceLabel='Distribución media de la categoría';warnings.push(`${product.name}: se ha aplicado la distribución media de ${product.category||'su categoría'} porque no existe histórico del producto.`);}
      const nomenclature=nomenclatures.get(manufacturingKey(product.productId))||nomenclatures.get(manufacturingKey(product.productCode)),categoryMean=(categoryRates[product.category]||[]).length?(categoryRates[product.category].reduce((a,b)=>a+b,0)/categoryRates[product.category].length):null,configuredRates=[...(nomenclature?.rates||[]),...Object.values(nomenclature?.variantRates||{})].filter(rate=>rate),weightedConfigured=variants.map(variant=>({quantity:Math.max(0,finiteNumber(variant.quantity,0)),rate:positiveNumber(nomenclature?.variantRates?.[variant.variantKey])||positiveNumber(nomenclature?.rates?.[Math.max(0,variant.variantIndex-1)])})).filter(item=>item.quantity&&item.rate),weightedConfiguredUnits=weightedConfigured.reduce((sum,item)=>sum+item.quantity,0),productMean=weightedConfiguredUnits?weightedConfigured.reduce((sum,item)=>sum+item.quantity*item.rate,0)/weightedConfiguredUnits:configuredRates.length?configuredRates.reduce((a,b)=>a+b,0)/configuredRates.length:null;
      if(!variants.length){const count=Math.max(1,nomenclature?.rates?.length||1);variants=Array.from({length:count},(_,variantIndex)=>({variantKey:String(variantIndex+1),variantName:`P${variantIndex+1}`,variantIndex:variantIndex+1,quantity:1}));variantSource=categoryMean?'category-average':'standard';sourceLabel=categoryMean?'Media de categoría':'Reparto estándar';warnings.push(`${product.name}: no existe distribución por variantes; se ha aplicado ${sourceLabel.toLowerCase()}.`);}
      const variantUnits=allocateIntegerTotal(normalizedUnits,variants.map(item=>item.quantity)),variantResults=[];let productHours=0,productResolvedUnits=0;
      variants.forEach((variant,variantIndex)=>{const units=variantUnits[variantIndex],exactRate=positiveNumber(nomenclature?.variantRates?.[variant.variantKey])||positiveNumber(nomenclature?.rates?.[Math.max(0,variant.variantIndex-1)]),rate=exactRate||productMean||categoryMean,rateSource=exactRate?'exact':productMean?'product-average':categoryMean?'category-average':'missing',hours=rate?units/rate:null;if(hours!=null&&Number.isFinite(hours)){productHours+=hours;productResolvedUnits+=units;if(variantSource==='explicit-forecast'&&rateSource==='exact')exactUnits+=units;else estimatedUnits+=units;}else unresolvedUnits+=units;if(!exactRate&&rate){warnings.push(`${product.name} ${variant.variantName}: falta rendimiento exacto; se ha aplicado la media de ${rateSource==='product-average'?'producto':'categoría'} (${Number(rate.toFixed(2))}).`);}if(!rate&&units>0)warnings.push(`${product.name} ${variant.variantName}: no existe ningún rendimiento aplicable para ${units} unidades.`);variantResults.push({variantKey:variant.variantKey,variantName:variant.variantName,quantity:units,rate:rate==null?null:Number(rate.toFixed(4)),rateSource,hours:hours==null?null:Number(hours.toFixed(4))});});
      const productDailyTotal=totalDaily(product.daily);if(productHours>0&&productDailyTotal>0)WEEK_DAYS.forEach(day=>{dailyHours[day.code]+=productHours*product.daily[day.code]/productDailyTotal;});else undistributedHours+=productHours;
      resultProducts.push({productId:product.productId,productCode:product.productCode,name:product.name,category:product.category,forecastUnits:normalizedUnits,originalForecastUnits:product.forecastUnits,variantSource,variantSourceLabel:sourceLabel,variants:variantResults,hours:Number(productHours.toFixed(4)),appliedRate:productHours>0?Number((productResolvedUnits/productHours).toFixed(4)):null,confidence:productResolvedUnits===normalizedUnits&&(variantSource==='explicit-forecast'&&variantResults.every(item=>item.rateSource==='exact'))?'calculated':productResolvedUnits>0?'estimated':'pending'});
    });
    const adjusted=normalizeDailyValues(input.adjustedDailyExpeditions),adjustedTotal=totalDaily(adjusted),available=WEEK_DAYS.filter(day=>adjusted[day.code]>0);if(undistributedHours>0){if(adjustedTotal)WEEK_DAYS.forEach(day=>{dailyHours[day.code]+=undistributedHours*adjusted[day.code]/adjustedTotal;});else{const target=available.length?available:WEEK_DAYS.slice(0,5);target.forEach(day=>{dailyHours[day.code]+=undistributedHours/target.length;});warnings.push('No había distribución diaria ajustada; las horas se han repartido entre los días laborables.');}}
    const forecastByCategory={};products.forEach((product,index)=>{forecastByCategory[product.category]=(forecastByCategory[product.category]||0)+normalizedTotals[index];});const purchasesByCategory={};(input.purchases||[]).forEach(item=>{const category=normalizeCode(item.category),units=purchaseQuantity(item);if(category&&units)purchasesByCategory[category]=(purchasesByCategory[category]||0)+units;});Object.entries(forecastByCategory).forEach(([category,units])=>{const purchased=purchasesByCategory[category]||0;if(!category||units<=0)return;if(!purchased)warnings.push(`La previsión incluye ${units} unidades de ${category}, pero no hay compras previstas de esa categoría.`);else{const differencePercent=(purchased-units)/units*100;if(Math.abs(differencePercent)>=20)warnings.push(`Las compras previstas de ${category} (${purchased}) son un ${Number(Math.abs(differencePercent).toFixed(2))}% ${differencePercent>0?'superiores':'inferiores'} a la previsión de Fabricación (${units}).`);}});
    const resolvedUnits=exactUnits+estimatedUnits,unresolvedPercentage=weeklyTotal?unresolvedUnits/weeklyTotal*100:0;if(weeklyTotal>0&&!resolvedUnits)blockingErrors.push('No existe ningún rendimiento aplicable para calcular Fabricación.');else if(unresolvedPercentage>=MATERIAL_MANUFACTURING_GAP_PERCENT)blockingErrors.push(`No puede calcularse el ${Number(unresolvedPercentage.toFixed(2))}% de Fabricación por falta de rendimientos aplicables.`);
    const weeklyHours=Object.values(dailyHours).reduce((sum,value)=>sum+value,0);if(!Number.isFinite(weeklyHours))blockingErrors.push('El cálculo de Fabricación ha producido un resultado no numérico.');const status=blockingErrors.length&&!resolvedUnits?'pending':unresolvedUnits>0?'partial':estimatedUnits>0?'estimated':'calculated';if(status==='estimated')warnings.unshift('Fabricación estimada a partir de previsiones, histórico y rendimientos medios.');
    return {weeklyHours:Number((Number.isFinite(weeklyHours)?weeklyHours:0).toFixed(4)),dailyHours:Object.fromEntries(WEEK_DAYS.map(day=>[day.code,Number(dailyHours[day.code].toFixed(4))])),products:resultProducts,status,warnings:[...new Set(warnings)],blockingErrors:[...new Set(blockingErrors)],calculationMeta:{recentWeeksUsed:[...recentWeeksUsed.values()],referenceWeekUsed:referenceUsed?{year:Number(reference.year),week:Number(reference.week)}:null,exactPercentage:weeklyTotal?Number((exactUnits/weeklyTotal*100).toFixed(2)):100,estimatedPercentage:weeklyTotal?Number((estimatedUnits/weeklyTotal*100).toFixed(2)):0,unresolvedPercentage:Number(unresolvedPercentage.toFixed(2)),forecastTotal,normalizedTotal:weeklyTotal}};
  }

  function buildProductionDailyBreakdown({days=WEEK_DAYS,activeTasks=[],calculatedHoursByTaskAndDay={}}={}){const columns=activeTasks.map(task=>({id:task.id,name:task.name,type:task.type,specialKind:task.specialKind||''})),rows=days.map(day=>{const values=Object.fromEntries(columns.map(task=>[task.id,finiteNumber(calculatedHoursByTaskAndDay?.[task.id]?.[day.code],0)])),total=Object.values(values).reduce((sum,value)=>sum+value,0);return {day:day.code,label:day.label,values,total};}),totalsByTask=Object.fromEntries(columns.map(task=>[task.id,rows.reduce((sum,row)=>sum+row.values[task.id],0)])),totalsByDay=Object.fromEntries(rows.map(row=>[row.day,row.total])),grandTotal=rows.reduce((sum,row)=>sum+row.total,0);return {columns,rows,totalsByTask,totalsByDay,grandTotal};}

  function variantRate(variantRates,key){return positiveNumber(variantRates instanceof Map?variantRates.get(key):variantRates?.[key]);}
  function specialTask(state,kind){return state.tasks.find(task=>task.specialKind===kind);}
  function calculateWeeklyPlan(planInput,stateInput,options={}){
    const state=createProductionState(stateInput),plan=normalizeWeeklyPlan(planInput);
    const days=Object.fromEntries(WEEK_DAYS.map(day=>[day.code,{reception:0,preassignment:0,manufacturing:0,shipping:0,otherMain:0,satellite:0,total:0}]));
    const issues=[],issueKeys=new Set(),activeTasks=state.tasks.filter(task=>task.active),hoursByTaskAndDay=Object.fromEntries(activeTasks.map(task=>[task.id,emptyDayValues(0)])),mainByTask=Object.fromEntries(state.tasks.filter(task=>task.type===TASK_TYPES.MAIN&&task.active).map(task=>[task.id,0]));
    const selectedSatelliteIds=new Set(plan.satelliteAssignments.map(item=>item.taskId));
    const satelliteByTask=Object.fromEntries(state.tasks.filter(task=>task.type===TASK_TYPES.SATELLITE&&task.active&&selectedSatelliteIds.has(task.id)).map(task=>[task.id,0]));
    const addIssue=(code,message,context={})=>{const key=JSON.stringify([code,message,context]);if(!issueKeys.has(key)){issueKeys.add(key);issues.push({code,message,...context});}};
    const balance=distributionBalance(plan);if(balance.difference)addIssue('DAILY_TOTAL_MISMATCH',`La distribución diaria difiere del total semanal en ${balance.difference>0?'+':''}${balance.difference} expediciones.`);
    const reception=specialTask(state,'reception'),preassignment=specialTask(state,'preassignment'),manufacturing=specialTask(state,'manufacturing'),shipping=specialTask(state,'shipping');
    const includeSpecial=task=>task?.active&&(task.type===TASK_TYPES.MAIN||selectedSatelliteIds.has(task.id));
    const addSpecialHours=(task,hours,day)=>{if(!task||!Number.isFinite(hours))return;if(task.type===TASK_TYPES.MAIN)mainByTask[task.id]=(mainByTask[task.id]??0)+hours;else satelliteByTask[task.id]=(satelliteByTask[task.id]??0)+hours;if(day&&hoursByTaskAndDay[task.id])hoursByTaskAndDay[task.id][day]+=hours;};
    const purchases=Array.isArray(options.purchases)?options.purchases:[];
    if(includeSpecial(reception)){
      if(!purchases.length)addIssue('RECEPTION_DATA_MISSING','Recepción pendiente de datos de Compras.');
      purchases.forEach(item=>{const day=validDay(item.day),category=normalizeCode(item.category),units=purchaseQuantity(item),rate=state.categoryRates[category]?.reception;if(!day||!PRODUCT_CATEGORIES.some(entry=>entry.code===category)||!units)return;if(rate==null)addIssue('RECEPTION_RATE_MISSING',`Falta el rendimiento de Recepción para ${PRODUCT_CATEGORIES.find(entry=>entry.code===category)?.label||category}.`,{day,category});else{const hours=units/rate;days[day].reception+=hours;addSpecialHours(reception,hours,day);}});
    }
    const categoryUnits=totalDaily(Object.fromEntries(WEEK_DAYS.map(day=>[day.code,Object.values(plan.categoryMix[day.code]).reduce((sum,value)=>sum+value,0)]))),needsCategoryMix=includeSpecial(manufacturing);
    if(needsCategoryMix&&categoryUnits>0&&balance.daily>0&&Math.abs(categoryUnits-balance.daily)>0.001)addIssue('CATEGORY_MIX_MISMATCH','El total del mix manual por categoría no coincide con la distribución diaria; no se usa como fuente del cálculo automático de Fabricación.');
    if(includeSpecial(preassignment)){const result=calculateDailyPreassignmentHours({purchases,categoryPerformances:state.categoryRates});WEEK_DAYS.forEach(day=>{const hours=result.byDay[day.code].totalHours;days[day.code].preassignment+=hours;addSpecialHours(preassignment,hours,day.code);});result.missingPerformances.forEach(category=>addIssue('PREASSIGNMENT_RATE_MISSING',`Falta el rendimiento de Preasignación para ${PRODUCT_CATEGORIES.find(item=>item.code===category)?.label||category}.`,{category}));if(!purchases.length)addIssue('PREASSIGNMENT_DATA_MISSING','Sin compras previstas para esta semana.');}
    let manufacturingPlan=null;
    if(includeSpecial(manufacturing)){
      if(Array.isArray(options.productForecast)){
        manufacturingPlan=calculateManufacturingPlan({weeklyTotal:balance.daily,productForecast:options.productForecast,variantForecast:options.variantForecast,nomenclatures:options.nomenclatures,recentHistory:options.recentHistory,referenceWeek:options.referenceWeek,generalHistory:options.generalHistory,purchases,adjustedDailyExpeditions:plan.distribution.adjusted});
        WEEK_DAYS.forEach(day=>{const hours=manufacturingPlan.dailyHours[day.code]||0;days[day.code].manufacturing+=hours;addSpecialHours(manufacturing,hours,day.code);});
        manufacturingPlan.warnings.forEach(message=>addIssue('MANUFACTURING_ESTIMATE',message));
        manufacturingPlan.blockingErrors.forEach(message=>addIssue('MANUFACTURING_PLAN_MISSING',message));
      }else{
        plan.variantMix.forEach(entry=>{const rate=variantRate(options.variantRates,entry.variantKey);if(rate==null)addIssue('MANUFACTURING_RATE_MISSING',`Falta el rendimiento de Fabricación de ${entry.productName||entry.productCode||entry.variantKey} ${entry.variantName||''}.`.trim(),{day:entry.day,variantKey:entry.variantKey});else{const hours=entry.units/rate;days[entry.day].manufacturing+=hours;addSpecialHours(manufacturing,hours,entry.day);}});
        if(!plan.variantMix.length&&balance.daily>0){const configured=Object.values(options.variantRates||{}).map(positiveNumber).filter(value=>value!=null),fallbackRate=positiveNumber(options.defaultManufacturingRate)||(configured.length?configured.reduce((a,b)=>a+b,0)/configured.length:null);if(fallbackRate){WEEK_DAYS.forEach(day=>{const units=plan.distribution.adjusted[day.code],hours=units/fallbackRate;days[day.code].manufacturing+=hours;addSpecialHours(manufacturing,hours,day.code);});addIssue('MANUFACTURING_FALLBACK','Se ha usado el rendimiento medio de las variantes configuradas para Fabricación.');}else addIssue('VARIANT_MIX_MISSING','La carga de Fabricación está pendiente: faltan previsiones por producto y rendimientos configurados.');}
      }
    }
    if(includeSpecial(shipping))WEEK_DAYS.forEach(day=>{const units=plan.distribution.adjusted[day.code];if(units>0&&state.shippingRate==null)addIssue('SHIPPING_RATE_MISSING','Falta configurar el rendimiento de expedición.');else if(state.shippingRate){const hours=units/state.shippingRate;days[day.code].shipping=hours;addSpecialHours(shipping,hours,day.code);}});
    let unassignedOtherMain=0,unassignedSatellite=0;
    function calculateAssignments(assignments,type){assignments.forEach(assignment=>{const task=state.tasks.find(item=>item.id===assignment.taskId&&item.type===type);if(!task||task.specialKind)return;if(!task.active){addIssue('TASK_INACTIVE_SKIPPED',`${task.name} está inactiva y se ha excluido del cálculo.`,{taskId:task.id});return;}const selected=WEEK_DAYS.filter(day=>assignment.days?.[day.code]?.selected);if(!selected.length){addIssue('TASK_DAY_PENDING',`${task.name} está pendiente de asignación diaria.`,{taskId:task.id});return;}selected.forEach(day=>{const quantity=assignment.days[day.code].quantity,hours=calculateTaskPersonHours(task,quantity);if(hours==null){addIssue('TASK_VALUE_MISSING',`Faltan datos para calcular ${task.name} el ${day.label}.`,{taskId:task.id,day:day.code});return;}const isMain=type===TASK_TYPES.MAIN;if(isMain){mainByTask[task.id]=(mainByTask[task.id]??0)+hours;days[day.code].otherMain+=hours;}else{satelliteByTask[task.id]=(satelliteByTask[task.id]??0)+hours;days[day.code].satellite+=hours;}hoursByTaskAndDay[task.id][day.code]+=hours;});});}
    calculateAssignments(plan.principalAssignments,TASK_TYPES.MAIN);calculateAssignments(plan.satelliteAssignments,TASK_TYPES.SATELLITE);
    state.tasks.filter(task=>task.type===TASK_TYPES.MAIN&&task.active&&!task.specialKind&&!plan.principalAssignments.some(item=>item.taskId===task.id)).forEach(task=>addIssue('PRINCIPAL_TASK_UNPLANNED',`${task.name} es una actividad principal activa y todavía no está planificada.`,{taskId:task.id}));
    WEEK_DAYS.forEach(day=>{const row=days[day.code];row.total=row.reception+row.preassignment+row.manufacturing+row.shipping+row.otherMain+row.satellite;});
    const weekly={reception:0,preassignment:0,manufacturing:0,shipping:0,otherMain:unassignedOtherMain,satellite:unassignedSatellite,mainTotal:0,satelliteTotal:0,total:0};
    WEEK_DAYS.forEach(day=>['reception','preassignment','manufacturing','shipping','otherMain','satellite'].forEach(key=>{weekly[key]+=days[day.code][key];}));
    const specialTasks={reception,preassignment,manufacturing,shipping};
    const specialMainTotal=Object.entries(specialTasks).reduce((sum,[kind,task])=>sum+(includeSpecial(task)&&task.type===TASK_TYPES.MAIN?weekly[kind]:0),0);
    const specialSatelliteTotal=Object.entries(specialTasks).reduce((sum,[kind,task])=>sum+(includeSpecial(task)&&task.type===TASK_TYPES.SATELLITE?weekly[kind]:0),0);
    weekly.mainTotal=specialMainTotal+weekly.otherMain;weekly.satelliteTotal=specialSatelliteTotal+weekly.satellite;weekly.total=weekly.mainTotal+weekly.satelliteTotal;
    const visibleTasks=activeTasks.filter(task=>task.type===TASK_TYPES.MAIN||selectedSatelliteIds.has(task.id)).sort((left,right)=>(left.type===TASK_TYPES.MAIN?0:1)-(right.type===TASK_TYPES.MAIN?0:1)),dailyBreakdown=buildProductionDailyBreakdown({days:WEEK_DAYS,activeTasks:visibleTasks,calculatedHoursByTaskAndDay:hoursByTaskAndDay});
    const blockingIssues=issues.filter(issue=>issue.code.endsWith('_MISSING')||['DAILY_TOTAL_MISMATCH','VARIANT_MIX_MISSING','PRINCIPAL_TASK_UNPLANNED'].includes(issue.code));
    return {plan,distribution:plan.distribution,days,weekly,mainByTask,satelliteByTask,hoursByTaskAndDay,dailyBreakdown,manufacturingPlan,forecastTotal:balance.daily,totalUsed:balance.used,difference:balance.difference,issues,blockingIssues,warnings:issues.filter(issue=>!issue.code.endsWith('_ERROR')),errors:issues.filter(issue=>issue.code.endsWith('_ERROR')),totals:{main:weekly.mainTotal,satellite:weekly.satelliteTotal,grandTotal:weekly.total},incomplete:blockingIssues.length>0};
  }
  function saveWeeklyPlan(stateInput,planInput,options={}){const state=createProductionState(stateInput,options),plan=normalizeWeeklyPlan({...planInput,updatedAt:isoNow(options.now)},options);return {ok:true,plan,state:{...state,weeklyPlans:{...state.weeklyPlans,[plan.key]:plan},updatedAt:plan.updatedAt}};}
  function validateWeeklyPlan(stateInput,planInput,options={}){const calculated=calculateWeeklyPlan(planInput,stateInput,options);if(calculated.incomplete)return {ok:false,errors:calculated.blockingIssues.map(issue=>issue.message),calculated,state:createProductionState(stateInput)};const now=isoNow(options.now),saved=saveWeeklyPlan(stateInput,{...calculated.plan,status:WEEK_STATUSES.VALIDATED,validatedAt:now,updatedAt:now},{...options,now});return {...saved,calculated};}
  function weeklyPlanFor(stateInput,year,week,options={}){const state=createProductionState(stateInput,options),key=weeklyPlanKey(year,week);return state.weeklyPlans[key]?normalizeWeeklyPlan(state.weeklyPlans[key],options):createWeeklyPlan(year,week,options);}
  function summarizeProductionState(stateInput){const state=createProductionState(stateInput),main=state.tasks.filter(task=>task.type===TASK_TYPES.MAIN),satellite=state.tasks.filter(task=>task.type===TASK_TYPES.SATELLITE),configuredCategoryRates=PRODUCT_CATEGORIES.reduce((count,category)=>count+(state.categoryRates[category.code].reception!=null?1:0)+(state.categoryRates[category.code].preassignment!=null?1:0),0);return {tasks:state.tasks.length,main:main.length,mainActive:main.filter(task=>task.active).length,satellite:satellite.length,activeSatellite:satellite.filter(task=>task.active).length,configuredCategoryRates,shippingConfigured:state.shippingRate!=null,weeklyPlans:Object.keys(state.weeklyPlans).length,validatedWeeks:Object.values(state.weeklyPlans).filter(plan=>plan.status===WEEK_STATUSES.VALIDATED).length,changes:state.changeHistory.length};}

  function calculateProductionWeek(input={}){const state=createProductionState({version:PRODUCTION_STATE_VERSION,tasks:input.tasks||[],categoryRates:input.categoryRates||input.categoryPerformances,shippingRate:input.shippingRate,weeklyPlans:{}}),plan=normalizeWeeklyPlan(input.plan||{year:Number(String(input.weekKey||'').slice(0,4)),week:Number(String(input.weekKey||'').slice(-2)),annualForecast:input.weeklyForecast,distribution:input.distribution,satelliteAssignments:input.satellitePlanning}),calculated=calculateWeeklyPlan(plan,state,{purchases:input.purchases,nomenclatures:input.nomenclatures,productForecast:input.productForecast,variantForecast:input.variantForecast,recentHistory:input.recentHistory,referenceWeek:input.referenceWeek,generalHistory:input.generalHistory,variantRates:input.variantRates,defaultManufacturingRate:input.defaultManufacturingRate});return {...calculated,calculationMeta:{weekKey:plan.key,calculatedAt:isoNow(),stateVersion:PRODUCTION_STATE_VERSION}};}

  return {PRODUCT_CATEGORIES,WEEK_DAYS,PRODUCTION_DAYS,PRODUCTION_STATE_VERSION,DEFAULT_PRODUCTION_DISTRIBUTION,RECENT_WEEKS_WEIGHT,REFERENCE_WEEK_WEIGHT,RECENT_VALID_WEEKS_COUNT,MATERIAL_MANUFACTURING_GAP_PERCENT,TASK_TYPES,TASK_PRIORITIES,TASK_MOBILITIES,CALCULATION_TYPES,WEEK_STATUSES,SPECIAL_TASK_DEFINITIONS,MAIN_TASK_DEFINITIONS,DEFAULT_SATELLITE_TASKS,DEFAULT_DISTRIBUTION_SETTINGS,createProductionState,normalizeTask,normalizeManufacturingRates,normalizeWeeklyPlan,normalizeAssignments,normalizeCode,weeklyPlanKey,isoWeekInfo,isoWeekRange,shiftWeek,createWeeklyPlan,weeklyPlanFor,saveWeeklyPlan,validateWeeklyPlan,weeklyTotalUsed,dailyPercentages,distributionBalance,applyDistributionProposal,spreadDailyDifference,calculateProductionDailyProposal,proposeDailyDistribution,calculateDailyPreassignmentHours,calculateDailyReceptionHours,calculateManufacturingPlan,buildProductionDailyBreakdown,calculateWeeklyPlan,calculateProductionWeek,updateMainTask,updateCategoryRate,updateShippingRate,addProductionTask,updateProductionTask,deactivateProductionTask,deleteProductionTask,calculateTaskPersonHours,taskTimingText,manufacturingTaskDescriptor,summarizeProductionState};
});
