const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const S=require('./staff.js');

const week={year:2026,week:33};
const days=['monday','tuesday','wednesday','thursday','friday'];
const schedule=(start='07:00',end='15:00')=>Object.fromEntries(S.DAYS.map(d=>[d.code,{enabled:days.includes(d.code),segments:days.includes(d.code)?[{start,end}]:[],breakMinutes:0}]));
const employee=(overrides={})=>S.normalizeEmployee({id:'employee-a',firstName:'Empleada',lastName:'A',weeklyContractHours:40,annualContractHours:1780,maxDailyHours:8,productivePercentage:92,weeklySchedule:schedule(),...overrides});
const availability=(e=employee(),absences=[],temporaryChanges=[])=>S.calculateEmployeeAvailability({employee:e,week,absences,temporaryChanges});
const named=(n,fn)=>test(`${n}. ${fn.name.replaceAll('_',' ')}`,fn);

named(1,function crear_empleado(){const r=S.upsertEmployee(S.createStaffState(),employee());assert.equal(r.ok,true);assert.equal(r.state.employees.length,1);});
named(2,function editar_empleado(){let st=S.upsertEmployee(S.createStaffState(),employee()).state;const r=S.upsertEmployee(st,{...st.employees[0],firstName:'Editada'});assert.equal(r.employee.firstName,'Editada');});
named(3,function desactivar_sin_perder_historico(){let st=S.upsertEmployee(S.createStaffState(),employee()).state;const r=S.deactivateOrDeleteEmployee(st,'employee-a',{hasHistoricalReferences:true});assert.equal(r.state.employees[0].status,'inactive');assert.ok(r.state.history.length>=2);});
named(4,function reactivar(){let st=S.setEmployeeStatus({employees:[employee({status:'inactive'})]},'employee-a','active').state;assert.equal(st.employees[0].status,'active');});
named(5,function validar_nombre_y_horas(){assert.equal(S.validateEmployee({firstName:'',weeklyContractHours:40}).ok,false);assert.equal(S.validateEmployee(employee()).ok,true);});
named(6,function horas_semanales_no_negativas(){assert.match(S.validateEmployee({...employee(),weeklyContractHours:-1}).errors.join(' '),/semanales/);});
named(7,function horas_anuales_no_negativas(){assert.match(S.validateEmployee({...employee(),annualContractHours:-1}).errors.join(' '),/anuales/);});
named(8,function porcentaje_productivo_entre_limites(){assert.equal(S.validateEmployee({...employee(),productivePercentage:101}).ok,false);});
named(9,function calcular_horas_de_un_tramo(){assert.equal(S.calculateScheduleSegmentHours({start:'07:00',end:'11:30'}),4.5);});
named(10,function calcular_varios_tramos(){assert.equal(S.calculateDailyScheduleHours({enabled:true,segments:[{start:'07:00',end:'11:00'},{start:'11:30',end:'15:00'}]}),7.5);});
named(11,function detectar_solapamientos(){assert.equal(S.validateDaySchedule({enabled:true,segments:[{start:'07:00',end:'12:00'},{start:'11:00',end:'15:00'}]}).ok,false);});
named(12,function detectar_salida_anterior(){assert.equal(S.validateDaySchedule({enabled:true,segments:[{start:'15:00',end:'07:00'}]}).ok,false);});
named(13,function calcular_horas_netas(){assert.equal(S.calculateDailyScheduleHours({enabled:true,segments:[{start:'07:00',end:'15:00'}],breakMinutes:30}),7.5);});
named(14,function detectar_exceso_diario(){assert.equal(S.validateDaySchedule({enabled:true,segments:[{start:'07:00',end:'16:00'}]},8).ok,false);});
named(15,function detectar_diferencia_con_jornada(){assert.ok(S.validateEmployee(employee({weeklyContractHours:30})).warnings.length);});
named(16,function fin_de_semana_oculto_por_defecto(){const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8'),ui=fs.readFileSync(path.join(__dirname,'staff-ui.js'),'utf8');assert.match(html,/id="staffShowWeekend"/);assert.match(ui,/weekend&&!el\('staffEditorShowWeekend'\)\.checked\?'hidden'/);});
named(17,function crear_plantilla_de_turno(){const r=S.upsertShiftTemplate(S.createStaffState(),{name:'Mañana',start:'07:00',end:'15:00'});assert.equal(r.ok,true);});
named(18,function asignar_turno_habitual(){assert.equal(employee({usualShiftId:'shift-1'}).usualShiftId,'shift-1');});
named(19,function asignar_turnos_alternativos(){assert.deepEqual(employee({allowedShiftIds:['shift-1','shift-2']}).allowedShiftIds,['shift-1','shift-2']);});
named(20,function desactivar_plantilla_sin_perderla(){let r=S.upsertShiftTemplate(S.createStaffState(),{id:'shift-1',name:'Mañana',start:'07:00',end:'15:00',active:false});assert.equal(r.state.shiftTemplates[0].active,false);});
named(21,function cargar_tareas_activas_de_produccion(){const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');assert.match(html,/productionState\.tasks\.filter\([^\n]+active/);});
named(22,function asignar_nivel(){assert.equal(employee({competencies:{task:{level:'expert'}}}).competencies.task.level,'expert');});
named(23,function marcar_especialidad(){assert.equal(employee({competencies:{task:{primary:true}}}).competencies.task.primary,true);});
named(24,function guardar_rendimiento_opcional(){assert.equal(employee({competencies:{task:{performance:115}}}).competencies.task.performance,115);});
named(25,function no_aplicar_rendimiento_individual(){const e=employee({productivePercentage:90,competencies:{task:{performance:200}}});assert.equal(availability(e).weeklyProductiveHours,36);});
named(26,function vacaciones_descuentan_horas(){assert.equal(availability(employee(),[{employeeId:'employee-a',type:'vacation',startDate:'2026-08-12',endDate:'2026-08-12'}]).weeklyAvailableHours,32);});
named(27,function ausencia_parcial_descuenta_tramo(){const a={employeeId:'employee-a',type:'partial',startDate:'2026-08-10',endDate:'2026-08-10',fullDay:false,startTime:'09:00',endTime:'11:00'};assert.equal(availability(employee(),[a]).availableHoursByDay.monday,6);});
named(28,function ausencia_cancelada_no_descuenta(){const a={employeeId:'employee-a',startDate:'2026-08-10',endDate:'2026-08-10',status:'cancelled'};assert.equal(availability(employee(),[a]).weeklyAvailableHours,40);});
named(29,function ausencia_tiene_prioridad_sobre_horario(){const a={employeeId:'employee-a',startDate:'2026-08-10',endDate:'2026-08-10'};assert.equal(availability(employee(),[a]).availableHoursByDay.monday,0);});
named(30,function no_borrar_historico_de_ausencias(){const st=S.normalizeStaffState({absences:[{id:'a',employeeId:'employee-a',startDate:'2026-01-01'}]});assert.equal(st.absences.length,1);});
named(31,function cambio_puntual_sustituye_horario(){const c={employeeId:'employee-a',date:'2026-08-10',type:'schedule-change',scheduleSegments:[{start:'08:00',end:'12:00'}]};assert.equal(availability(employee(),[],[c]).availableHoursByDay.monday,4);});
named(32,function dia_libre_deja_cero(){const c={employeeId:'employee-a',date:'2026-08-10',type:'day-off'};assert.equal(availability(employee(),[],[c]).availableHoursByDay.monday,0);});
named(33,function horario_adicional_aumenta(){const c={employeeId:'employee-a',date:'2026-08-10',type:'additional-availability',hours:2};assert.equal(availability(employee(),[],[c]).availableHoursByDay.monday,10);});
named(34,function ausencia_prevalece_sobre_cambio(){const a={employeeId:'employee-a',startDate:'2026-08-10',endDate:'2026-08-10'},c={employeeId:'employee-a',date:'2026-08-10',type:'additional-availability',hours:2};assert.equal(availability(employee(),[a],[c]).availableHoursByDay.monday,0);});
named(35,function calcular_disponibilidad_diaria(){assert.equal(availability().availableHoursByDay.monday,8);});
named(36,function calcular_disponibilidad_semanal(){assert.equal(availability().weeklyAvailableHours,40);});
named(37,function calcular_horas_productivas(){assert.ok(Math.abs(availability().weeklyProductiveHours-36.8)<1e-9);});
named(38,function sumar_equipo(){const b=employee({id:'employee-b',firstName:'B',weeklyContractHours:30,weeklySchedule:schedule('07:00','13:00'),productivePercentage:90,maxDailyHours:8});const c=S.calculateTeamCapacity({employees:[employee(),b],week});assert.equal(c.weeklyAvailableHours,70);});
named(39,function excluir_inactivos(){const c=S.calculateTeamCapacity({employees:[employee(),employee({id:'employee-x',status:'inactive'})],week});assert.equal(c.activeEmployees,1);});
named(40,function descontar_ausencias_del_equipo(){const a={employeeId:'employee-a',startDate:'2026-08-12',endDate:'2026-08-12'};assert.equal(S.calculateTeamCapacity({employees:[employee()],week,absences:[a]}).weeklyAvailableHours,32);});
named(41,function aplicar_cambios_temporales_al_equipo(){const c={employeeId:'employee-a',date:'2026-08-10',type:'day-off'};assert.equal(S.calculateTeamCapacity({employees:[employee()],week,temporaryChanges:[c]}).weeklyAvailableHours,32);});
named(42,function comparar_capacidad_con_produccion(){const cap=S.calculateTeamCapacity({employees:[employee()],week});const r=S.compareCapacityWithProduction({teamCapacity:cap,productionRequirements:{monday:10}});assert.equal(r.rows[0].status,'deficit');});
named(43,function guardar_empleado_desde_interfaz(){const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8'),ui=fs.readFileSync(path.join(__dirname,'staff-ui.js'),'utf8');assert.match(html,/id="btnStaffSaveEmployee"/);assert.match(ui,/upsertEmployee\(staffState/);});
named(44,function recargar_estado(){const original=S.normalizeStaffState({employees:[employee()]});assert.deepEqual(S.normalizeStaffState(JSON.parse(JSON.stringify(original))),original);});
named(45,function migracion_idempotente(){const once=S.migrateStaffState({employees:[employee()]});assert.deepEqual(S.migrateStaffState(once),once);});
named(46,function no_escribir_automaticamente_en_supabase(){const source=fs.readFileSync(path.join(__dirname,'staff.js'),'utf8');assert.doesNotMatch(source,/supabase|saveState/i);});
named(47,function mantener_json_fuera_del_modulo(){for(const file of ['staff.js','staff.test.js'])assert.doesNotMatch(fs.readFileSync(path.join(__dirname,file),'utf8'),/aquarelle-stock-datos\.json/);});
named(48,function registrar_cambio_de_jornada(){const r=S.recordStaffChange(S.createStaffState(),{employeeId:'employee-a',field:'weeklyContractHours',oldValue:40,newValue:35});assert.equal(r.history[0].field,'weeklyContractHours');});
named(49,function registrar_cambio_de_horario(){const r=S.recordStaffChange(S.createStaffState(),{employeeId:'employee-a',field:'weeklySchedule',oldValue:{},newValue:schedule()});assert.equal(r.history[0].field,'weeklySchedule');});
named(50,function registrar_cambio_de_especialidad(){const r=S.recordStaffChange(S.createStaffState(),{employeeId:'employee-a',field:'competencies',oldValue:{},newValue:{task:{primary:true}}});assert.equal(r.history[0].newValue.task.primary,true);});
named(51,function no_alterar_semana_historica(){let st=S.snapshotStaffWeek({employees:[employee()]},week);const snap=JSON.stringify(st.weeklyPlans);st=S.upsertEmployee(st,{...st.employees[0],firstName:'Otra'}).state;assert.equal(JSON.stringify(st.weeklyPlans),snap);});
