(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.AquarelleStaff=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const VERSION=1;
  const DAYS=[
    {code:'monday',label:'Lunes'},{code:'tuesday',label:'Martes'},{code:'wednesday',label:'Miércoles'},
    {code:'thursday',label:'Jueves'},{code:'friday',label:'Viernes'},{code:'saturday',label:'Sábado'},{code:'sunday',label:'Domingo'}
  ];
  const clone=value=>JSON.parse(JSON.stringify(value));
  const text=value=>String(value==null?'':value).trim();
  const number=(value,fallback=0)=>{const raw=String(value??'').trim();if(!raw)return fallback;const parsed=Number(raw.replace(',','.'));return Number.isFinite(parsed)?parsed:fallback;};
  const bounded=(value,min,max,fallback=min)=>Math.min(max,Math.max(min,number(value,fallback)));
  const isoNow=()=>new Date().toISOString();
  const id=(prefix,value)=>text(value)||`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
  const timeMinutes=value=>{const match=text(value).match(/^(\d{1,2}):(\d{2})$/);if(!match)return null;const hours=Number(match[1]),minutes=Number(match[2]);return hours<=23&&minutes<=59?hours*60+minutes:null;};
  const emptyDay=()=>({enabled:false,segments:[],breakMinutes:0,earliestStart:'',latestEnd:'',flexMinutes:0,canExtend:false,canStartEarlier:false,canSplit:false});
  const defaultSchedule=()=>Object.fromEntries(DAYS.map((day,index)=>[day.code,index<5?{...emptyDay(),enabled:true,segments:[{start:'07:00',end:'15:00'}],breakMinutes:0}:emptyDay()]));
  const normalizeSegment=value=>({start:text(value?.start),end:text(value?.end)});
  function normalizeDaySchedule(value){const source=value&&typeof value==='object'?value:{},segments=Array.isArray(source.segments)?source.segments.map(normalizeSegment):[];return {...emptyDay(),...clone(source),enabled:source.enabled===true,segments,breakMinutes:Math.max(0,number(source.breakMinutes)),flexMinutes:Math.max(0,number(source.flexMinutes)),canExtend:source.canExtend===true,canStartEarlier:source.canStartEarlier===true,canSplit:source.canSplit===true};}
  function normalizeWeeklySchedule(value){const source=value&&typeof value==='object'?value:{};return Object.fromEntries(DAYS.map(day=>[day.code,normalizeDaySchedule(source[day.code])]));}
  function calculateScheduleSegmentHours(segment){const start=timeMinutes(segment?.start),end=timeMinutes(segment?.end);return start==null||end==null||end<=start?0:(end-start)/60;}
  function validateDaySchedule(daySchedule,maxDailyHours=24){const day=normalizeDaySchedule(daySchedule),errors=[];if(!day.enabled)return {ok:true,errors:[],hours:0};const intervals=day.segments.map((segment,index)=>({index,start:timeMinutes(segment.start),end:timeMinutes(segment.end)}));intervals.forEach(item=>{if(item.start==null||item.end==null)errors.push(`El tramo ${item.index+1} no tiene horas válidas.`);else if(item.end<=item.start)errors.push(`El tramo ${item.index+1} termina antes de empezar.`);});const valid=intervals.filter(item=>item.start!=null&&item.end!=null&&item.end>item.start).sort((a,b)=>a.start-b.start);for(let index=1;index<valid.length;index++)if(valid[index].start<valid[index-1].end)errors.push('Hay tramos horarios solapados.');const gross=valid.reduce((sum,item)=>sum+(item.end-item.start)/60,0),hours=Math.max(0,gross-day.breakMinutes/60);if(hours>number(maxDailyHours,24)+1e-9)errors.push(`El horario supera el máximo diario de ${maxDailyHours} horas.`);return {ok:errors.length===0,errors,hours};}
  function calculateDailyScheduleHours(daySchedule){return validateDaySchedule(daySchedule,Number.POSITIVE_INFINITY).hours;}
  function calculateWeeklyScheduleHours(weeklySchedule){const normalized=normalizeWeeklySchedule(weeklySchedule);return Object.fromEntries([...DAYS.map(day=>[day.code,calculateDailyScheduleHours(normalized[day.code])]),['total',DAYS.reduce((sum,day)=>sum+calculateDailyScheduleHours(normalized[day.code]),0)]]);}
  function normalizeAvailability(value){const source=value&&typeof value==='object'?value:{};return {...clone(source),canWorkSaturday:source.canWorkSaturday===true,canWorkSunday:source.canWorkSunday===true,canChangeShift:source.canChangeShift===true,minimumChangeNoticeHours:Math.max(0,number(source.minimumChangeNoticeHours))};}
  function normalizeRestrictions(value){const source=value&&typeof value==='object'?value:{};return {earliestStart:text(source.earliestStart),latestEnd:text(source.latestEnd),forbiddenDays:Array.isArray(source.forbiddenDays)?[...new Set(source.forbiddenDays.filter(day=>DAYS.some(item=>item.code===day)))]:[],noSplitShift:source.noSplitShift===true,noSaturday:source.noSaturday===true,noSunday:source.noSunday===true,forbiddenTaskIds:Array.isArray(source.forbiddenTaskIds)?[...new Set(source.forbiddenTaskIds.map(text).filter(Boolean))]:[],supervisedTaskIds:Array.isArray(source.supervisedTaskIds)?[...new Set(source.supervisedTaskIds.map(text).filter(Boolean))]:[],canOpenAlone:source.canOpenAlone===true,canCloseAlone:source.canCloseAlone===true,canUseMachinery:source.canUseMachinery===true,needsPartner:source.needsPartner===true,temporary:Array.isArray(source.temporary)?clone(source.temporary):[],notes:text(source.notes)};}
  function normalizeCompetencies(value){const source=value&&typeof value==='object'?value:{};return Object.fromEntries(Object.entries(source).map(([taskId,item])=>[text(taskId),{level:['none','training','autonomous','expert','trainer'].includes(item?.level)?item.level:'none',primary:item?.primary===true,preferred:item?.preferred===true,avoid:item?.avoid===true,performance:item?.performance==null||text(item.performance)===''?null:bounded(item.performance,0,300,100),notes:text(item?.notes),updatedAt:item?.updatedAt||isoNow()}]));}
  function normalizeEmployee(employee={}){const now=isoNow(),weeklyContractHours=Math.max(0,number(employee.weeklyContractHours,40)),maxWeeklyHours=Math.max(0,number(employee.maxWeeklyHours,weeklyContractHours));return {id:id('employee',employee.id),firstName:text(employee.firstName),lastName:text(employee.lastName),shortName:text(employee.shortName),internalCode:text(employee.internalCode),status:['active','temporary-leave','vacation','inactive'].includes(employee.status)?employee.status:'active',startDate:text(employee.startDate),contractType:['permanent','temporary','campaign','other'].includes(employee.contractType)?employee.contractType:'permanent',weeklyContractHours,annualContractHours:Math.max(0,number(employee.annualContractHours,1780)),workdayType:['full-time','part-time','flexible','campaign'].includes(employee.workdayType)?employee.workdayType:'full-time',workdayPercentage:bounded(employee.workdayPercentage,0,100,100),maxDailyHours:Math.max(0,number(employee.maxDailyHours,8)),maxWeeklyHours,maxDaysPerWeek:Math.round(bounded(employee.maxDaysPerWeek,0,7,5)),usualBreakMinutes:Math.max(0,number(employee.usualBreakMinutes)),productivePercentage:bounded(employee.productivePercentage,0,100,92),allowsExtraHours:employee.allowsExtraHours===true,maxExtraHoursPerWeek:Math.max(0,number(employee.maxExtraHoursPerWeek)),usualShiftId:text(employee.usualShiftId)||null,allowedShiftIds:Array.isArray(employee.allowedShiftIds)?[...new Set(employee.allowedShiftIds.map(text).filter(Boolean))]:[],forbiddenShiftIds:Array.isArray(employee.forbiddenShiftIds)?[...new Set(employee.forbiddenShiftIds.map(text).filter(Boolean))]:[],shiftPreference:text(employee.shiftPreference),weeklySchedule:normalizeWeeklySchedule(employee.weeklySchedule||defaultSchedule()),availability:normalizeAvailability(employee.availability),competencies:normalizeCompetencies(employee.competencies),restrictions:normalizeRestrictions(employee.restrictions),workdayNotes:text(employee.workdayNotes),notes:text(employee.notes),createdAt:employee.createdAt||now,updatedAt:employee.updatedAt||now,deletedAt:employee.deletedAt||null};}
  function validateEmployee(employee){const source=employee&&typeof employee==='object'?employee:{},item=normalizeEmployee(source),errors=[],warnings=[];if(!item.firstName)errors.push('El nombre es obligatorio.');if(number(source.weeklyContractHours,40)<0)errors.push('Las horas semanales no pueden ser negativas.');if(number(source.annualContractHours,1780)<0)errors.push('Las horas anuales no pueden ser negativas.');if(number(source.productivePercentage,92)<0||number(source.productivePercentage,92)>100)errors.push('El porcentaje productivo debe estar entre 0 y 100.');DAYS.forEach(day=>{const check=validateDaySchedule(item.weeklySchedule[day.code],item.maxDailyHours);check.errors.forEach(message=>errors.push(`${day.label}: ${message}`));});const scheduled=calculateWeeklyScheduleHours(item.weeklySchedule).total;if(Math.abs(scheduled-item.weeklyContractHours)>0.01)warnings.push(`El horario habitual suma ${scheduled} h y la jornada contratada ${item.weeklyContractHours} h.`);return {ok:errors.length===0,errors,warnings,employee:item};}
  function normalizeShiftTemplate(value={}){return {id:id('shift',value.id),name:text(value.name),start:text(value.start),end:text(value.end),breakMinutes:Math.max(0,number(value.breakMinutes)),usualDays:Array.isArray(value.usualDays)?value.usualDays.filter(day=>DAYS.some(item=>item.code===day)):[],description:text(value.description),active:value.active!==false,createdAt:value.createdAt||isoNow(),updatedAt:value.updatedAt||isoNow()};}
  function validateShiftTemplate(value){const shift=normalizeShiftTemplate(value),errors=[];if(!shift.name)errors.push('El nombre del turno es obligatorio.');if(calculateScheduleSegmentHours(shift)<=0)errors.push('El horario del turno no es válido.');return {ok:errors.length===0,errors,shift};}
  function normalizeAbsence(value={}){return {id:id('absence',value.id),employeeId:text(value.employeeId),type:['vacation','sick-leave','permission','training','compensatory','partial','other'].includes(value.type)?value.type:'vacation',startDate:text(value.startDate),endDate:text(value.endDate)||text(value.startDate),fullDay:value.fullDay!==false,startTime:value.fullDay===false?text(value.startTime)||null:null,endTime:value.fullDay===false?text(value.endTime)||null:null,unavailableHours:value.unavailableHours==null||text(value.unavailableHours)===''?null:Math.max(0,number(value.unavailableHours)),status:['planned','confirmed','cancelled'].includes(value.status)?value.status:'confirmed',notes:text(value.notes),createdAt:value.createdAt||isoNow(),updatedAt:value.updatedAt||isoNow()};}
  function normalizeTemporaryChange(value={}){return {id:id('change',value.id),employeeId:text(value.employeeId),date:text(value.date),type:['schedule-change','additional-availability','reduced-hours','day-off','special-shift','campaign'].includes(value.type)?value.type:'schedule-change',scheduleSegments:Array.isArray(value.scheduleSegments)?value.scheduleSegments.map(normalizeSegment):[],breakMinutes:Math.max(0,number(value.breakMinutes)),hours:value.hours==null||text(value.hours)===''?null:Math.max(0,number(value.hours)),notes:text(value.notes),status:value.status==='cancelled'?'cancelled':'active',createdAt:value.createdAt||isoNow(),updatedAt:value.updatedAt||isoNow()};}
  function isoWeekStart(year,week){const jan4=new Date(Date.UTC(Number(year),0,4)),day=jan4.getUTCDay()||7,monday=new Date(jan4);monday.setUTCDate(jan4.getUTCDate()-day+1+(Math.max(1,Number(week))-1)*7);return monday;}
  function weekDates(week){const monday=isoWeekStart(week?.year,week?.week);return Object.fromEntries(DAYS.map((day,index)=>{const date=new Date(monday);date.setUTCDate(monday.getUTCDate()+index);return [day.code,date.toISOString().slice(0,10)];}));}
  const eventCoversDate=(event,date)=>event.status!=='cancelled'&&event.startDate<=date&&event.endDate>=date;
  function absenceHoursForDate(absences,date,baseHours){const events=absences.filter(event=>eventCoversDate(event,date));if(events.some(event=>event.fullDay))return baseHours;return Math.min(baseHours,events.reduce((sum,event)=>sum+(event.unavailableHours!=null?event.unavailableHours:calculateScheduleSegmentHours({start:event.startTime,end:event.endTime})),0));}
  function changedHoursForDate(changes,date,baseHours){const active=changes.filter(item=>item.status!=='cancelled'&&item.date===date);if(!active.length)return {hours:baseHours,added:0,description:''};if(active.some(item=>item.type==='day-off'))return {hours:0,added:-baseHours,description:'Día libre'};const replacement=active.find(item=>['schedule-change','special-shift','campaign'].includes(item.type));let hours=replacement?Math.max(0,replacement.scheduleSegments.reduce((sum,segment)=>sum+calculateScheduleSegmentHours(segment),0)-replacement.breakMinutes/60):baseHours;const reduced=active.find(item=>item.type==='reduced-hours');if(reduced)hours=reduced.hours==null?hours:Math.min(hours,reduced.hours);const additional=active.filter(item=>item.type==='additional-availability').reduce((sum,item)=>sum+(item.hours!=null?item.hours:item.scheduleSegments.reduce((total,segment)=>total+calculateScheduleSegmentHours(segment),0)),0);hours+=additional;return {hours,added:hours-baseHours,description:active.map(item=>item.type).join(', ')};}
  function calculateEmployeeAvailability({employee,week,absences=[],temporaryChanges=[],assignedHoursByDay={}}={}){const item=normalizeEmployee(employee),dates=weekDates(week),employeeAbsences=absences.map(normalizeAbsence).filter(event=>event.employeeId===item.id&&event.status!=='cancelled'),employeeChanges=temporaryChanges.map(normalizeTemporaryChange).filter(event=>event.employeeId===item.id&&event.status!=='cancelled'),availableHoursByDay={},productiveHoursByDay={},absenceHoursByDay={},changeHoursByDay={},assignedByDay={},warnings=[];DAYS.forEach(day=>{const base=calculateDailyScheduleHours(item.weeklySchedule[day.code]),changed=changedHoursForDate(employeeChanges,dates[day.code],base),absence=absenceHoursForDate(employeeAbsences,dates[day.code],changed.hours),available=item.status==='active'?Math.max(0,changed.hours-absence):0,productive=available*item.productivePercentage/100,assigned=Math.max(0,number(assignedHoursByDay[day.code]));availableHoursByDay[day.code]=available;productiveHoursByDay[day.code]=productive;absenceHoursByDay[day.code]=absence;changeHoursByDay[day.code]=changed.added;assignedByDay[day.code]=assigned;if(assigned>available+1e-9)warnings.push(`${day.label}: las horas asignadas superan la disponibilidad.`);});const sum=values=>DAYS.reduce((total,day)=>total+values[day.code],0),weeklyAvailableHours=sum(availableHoursByDay),weeklyProductiveHours=sum(productiveHoursByDay),weeklyAbsenceHours=sum(absenceHoursByDay),weeklyChangeHours=sum(changeHoursByDay),weeklyAssignedHours=sum(assignedByDay);return {employeeId:item.id,week:{year:Number(week?.year),week:Number(week?.week)},dates,availableHoursByDay,productiveHoursByDay,absenceHoursByDay,changeHoursByDay,assignedHoursByDay:assignedByDay,weeklyContractHours:item.weeklyContractHours,weeklyUsualHours:calculateWeeklyScheduleHours(item.weeklySchedule).total,weeklyAvailableHours,weeklyProductiveHours,weeklyAbsenceHours,weeklyChangeHours,weeklyAssignedHours,weeklyRemainingHours:Math.max(0,weeklyAvailableHours-weeklyAssignedHours),warnings};}
  function calculateTeamCapacity({employees=[],week,absences=[],temporaryChanges=[],assignedHours={}}={}){const active=employees.map(normalizeEmployee).filter(employee=>employee.status==='active'),people=active.map(employee=>calculateEmployeeAvailability({employee,week,absences,temporaryChanges,assignedHoursByDay:assignedHours[employee.id]||{}})),availableHoursByDay=Object.fromEntries(DAYS.map(day=>[day.code,people.reduce((sum,item)=>sum+item.availableHoursByDay[day.code],0)])),productiveHoursByDay=Object.fromEntries(DAYS.map(day=>[day.code,people.reduce((sum,item)=>sum+item.productiveHoursByDay[day.code],0)]));return {week:{year:Number(week?.year),week:Number(week?.week)},people,activeEmployees:active.length,availableHoursByDay,productiveHoursByDay,weeklyAvailableHours:DAYS.reduce((sum,day)=>sum+availableHoursByDay[day.code],0),weeklyProductiveHours:DAYS.reduce((sum,day)=>sum+productiveHoursByDay[day.code],0),weeklyAbsenceHours:people.reduce((sum,item)=>sum+item.weeklyAbsenceHours,0),weeklyContractHours:active.reduce((sum,item)=>sum+item.weeklyContractHours,0),warnings:people.flatMap(item=>item.warnings)};}
  function compareCapacityWithProduction({teamCapacity,productionRequirements={}}={}){const rows=DAYS.map(day=>{const required=Math.max(0,number(productionRequirements[day.code])),available=Math.max(0,number(teamCapacity?.productiveHoursByDay?.[day.code])),difference=available-required;return {day:day.code,label:day.label,requiredHours:required,productiveHours:available,difference,status:difference<0?'deficit':'surplus',message:difference<0?`${day.label}: déficit de ${Math.abs(difference).toFixed(2)} horas-persona.`:`${day.label}: capacidad sobrante de ${difference.toFixed(2)} horas-persona.`};});return {rows,weeklyRequiredHours:rows.reduce((sum,row)=>sum+row.requiredHours,0),weeklyProductiveHours:rows.reduce((sum,row)=>sum+row.productiveHours,0),weeklyDifference:rows.reduce((sum,row)=>sum+row.difference,0),warnings:rows.filter(row=>row.difference<0).map(row=>row.message)};}
  function defaultGeneratorModel(){return {mode:'preserve-usual',requirementBlocks:[],assignments:[],priorities:['fixed-time','required-skills','absences-restrictions','workday-rest','usual-schedule','task-changes','preassignment-manufacturing','shipping','satellite','balance','deficit','locked-regeneration']};}
  function createStaffState(){return {version:VERSION,employees:[],shiftTemplates:[],absences:[],temporaryChanges:[],weeklyPlans:{},history:[],generator:defaultGeneratorModel(),updatedAt:isoNow()};}
  function normalizeStaffState(state){const source=state&&typeof state==='object'?state:{},base=createStaffState();return {...base,...clone(source),version:VERSION,employees:Array.isArray(source.employees)?source.employees.map(normalizeEmployee):[],shiftTemplates:Array.isArray(source.shiftTemplates)?source.shiftTemplates.map(normalizeShiftTemplate):[],absences:Array.isArray(source.absences)?source.absences.map(normalizeAbsence):[],temporaryChanges:Array.isArray(source.temporaryChanges)?source.temporaryChanges.map(normalizeTemporaryChange):[],weeklyPlans:source.weeklyPlans&&typeof source.weeklyPlans==='object'&&!Array.isArray(source.weeklyPlans)?clone(source.weeklyPlans):{},history:Array.isArray(source.history)?clone(source.history):[],generator:{...defaultGeneratorModel(),...(source.generator&&typeof source.generator==='object'?clone(source.generator):{})}};}
  function migrateStaffState(state){return normalizeStaffState(state);}
  function recordStaffChange(state,{employeeId,field,oldValue,newValue,comment='',at=isoNow()}={}){const next=normalizeStaffState(state);next.history.push({id:id('staff-history'),employeeId:text(employeeId),at,field:text(field),oldValue:clone(oldValue??null),newValue:clone(newValue??null),comment:text(comment)});next.updatedAt=at;return next;}
  function upsertEmployee(state,employee,{comment=''}={}){let next=normalizeStaffState(state);const check=validateEmployee(employee);if(!check.ok)return {ok:false,errors:check.errors,warnings:check.warnings,state:next};const index=next.employees.findIndex(item=>item.id===check.employee.id),old=index>=0?next.employees[index]:null,saved={...check.employee,updatedAt:isoNow()};if(index>=0)next.employees[index]=saved;else next.employees.push(saved);if(!old)next=recordStaffChange(next,{employeeId:saved.id,field:'employee-created',oldValue:null,newValue:saved,comment});else{const tracked=['status','weeklyContractHours','annualContractHours','workdayType','workdayPercentage','productivePercentage','weeklySchedule','usualShiftId','allowedShiftIds','forbiddenShiftIds','competencies','restrictions'];tracked.forEach(field=>{if(JSON.stringify(old[field])!==JSON.stringify(saved[field]))next=recordStaffChange(next,{employeeId:saved.id,field,oldValue:old[field],newValue:saved[field],comment});});if(!tracked.some(field=>JSON.stringify(old[field])!==JSON.stringify(saved[field])))next=recordStaffChange(next,{employeeId:saved.id,field:'employee-updated',oldValue:{firstName:old.firstName,lastName:old.lastName,notes:old.notes},newValue:{firstName:saved.firstName,lastName:saved.lastName,notes:saved.notes},comment});}return {ok:true,errors:[],warnings:check.warnings,state:next,employee:saved};}
  function setEmployeeStatus(state,employeeId,status,{comment=''}={}){const next=normalizeStaffState(state),employee=next.employees.find(item=>item.id===employeeId);if(!employee)return {ok:false,errors:['Empleado no encontrado.'],state:next};const old=employee.status;employee.status=['active','temporary-leave','vacation','inactive'].includes(status)?status:'inactive';employee.updatedAt=isoNow();return {ok:true,state:recordStaffChange(next,{employeeId,field:'status',oldValue:old,newValue:employee.status,comment}),employee};}
  function duplicateEmployee(state,employeeId){const next=normalizeStaffState(state),source=next.employees.find(item=>item.id===employeeId);if(!source)return {ok:false,errors:['Empleado no encontrado.'],state:next};const copy=normalizeEmployee({...clone(source),id:'',firstName:`${source.firstName} copia`,internalCode:'',createdAt:'',updatedAt:''});return upsertEmployee(next,copy,{comment:'Duplicación de ficha'});}
  function deactivateOrDeleteEmployee(state,employeeId,{hasHistoricalReferences=true,comment=''}={}){const next=normalizeStaffState(state),employee=next.employees.find(item=>item.id===employeeId);if(!employee)return {ok:false,errors:['Empleado no encontrado.'],state:next};if(hasHistoricalReferences)return setEmployeeStatus(next,employeeId,'inactive',{comment:comment||'Desactivación conservando histórico'});const filtered=next.employees.filter(item=>item.id!==employeeId);return {ok:true,state:recordStaffChange({...next,employees:filtered},{employeeId,field:'employee-deleted',oldValue:{id:employee.id,firstName:employee.firstName,lastName:employee.lastName},newValue:null,comment})};}
  function upsertShiftTemplate(state,template){const next=normalizeStaffState(state),check=validateShiftTemplate(template);if(!check.ok)return {ok:false,errors:check.errors,state:next};const index=next.shiftTemplates.findIndex(item=>item.id===check.shift.id);if(index>=0)next.shiftTemplates[index]=check.shift;else next.shiftTemplates.push(check.shift);return {ok:true,state:next,shift:check.shift};}
  function snapshotStaffWeek(state,week,{productionRequirements={}}={}){const next=normalizeStaffState(state),key=`${Number(week.year)}-${String(Number(week.week)).padStart(2,'0')}`,capacity=calculateTeamCapacity({employees:next.employees,week,absences:next.absences,temporaryChanges:next.temporaryChanges});next.weeklyPlans[key]={key,year:Number(week.year),week:Number(week.week),createdAt:isoNow(),employees:next.employees.filter(item=>item.status==='active').map(item=>({id:item.id,firstName:item.firstName,lastName:item.lastName,shortName:item.shortName,weeklyContractHours:item.weeklyContractHours,productivePercentage:item.productivePercentage,usualShiftId:item.usualShiftId})),capacity:clone(capacity),productionRequirements:clone(productionRequirements)};return next;}
  return {VERSION,DAYS,createStaffState,normalizeEmployee,validateEmployee,calculateScheduleSegmentHours,validateDaySchedule,calculateDailyScheduleHours,calculateWeeklyScheduleHours,normalizeShiftTemplate,validateShiftTemplate,normalizeAbsence,normalizeTemporaryChange,calculateEmployeeAvailability,calculateTeamCapacity,compareCapacityWithProduction,normalizeStaffState,migrateStaffState,recordStaffChange,upsertEmployee,setEmployeeStatus,duplicateEmployee,deactivateOrDeleteEmployee,upsertShiftTemplate,snapshotStaffWeek,classifyLevel:value=>normalizeCompetencies({task:{level:value}}).task.level,defaultGeneratorModel,weekDates};
});
